const {chromium}=require('/Users/apololira/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
let saved={},exported=null;
await page.route('http://studio.test/**',async route=>{
const url=new URL(route.request().url()),p=url.pathname;
if(p==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:fs.readFileSync('tmp/studio-editor-check/index.html','utf8')});
if(p.startsWith('/static/'))return route.fulfill({path:'aicentralv2'+p});
if(p==='/clip.mp4')return route.fulfill({path:'tmp/studio-editor-check/clip.mp4',contentType:'video/mp4'});
let data={};
if(p.endsWith('/swap/library'))data={items:url.searchParams.get('media')==='video'?[{id:'clip1',name:'Vídeo de teste',duration:3,video_url:'/clip.mp4'}]:[{id:'still1',name:'Criativo vertical',width:90,height:160,aspect_ratio:'16:9',image_url:'/static/images/canais/prime-video.svg'}]};
if(p.endsWith('/clips'))data={items:[]};
if(p.endsWith('/sounds'))data={items:JSON.parse(fs.readFileSync('aicentralv2/static/audio/studio/catalog.json'))};
if(p.endsWith('/projects'))data=route.request().method()==='POST'?(saved=JSON.parse(route.request().postData()).document,{id:'project',revision:1,document:saved}):{items:[]};
if(p.endsWith('/projects/project'))data={id:'project',revision:2,document:(saved=JSON.parse(route.request().postData()).document)};
if(p.endsWith('/jobs'))data={items:[],exports:[]};
if(p.endsWith('/video-project'))data={project:{}};
if(p.endsWith('/inspect')||p.endsWith('/tasks'))data={has_audio:true,waveform:[],frames:[]};
if(p.endsWith('/tasks')&&JSON.parse(route.request().postData()).kind==='transcribe')data={id:'transcript',kind:'transcribe',status:'ready',result:{captions:[{start:.1,end:1,text:'Legenda automática'}],language:'pt'}};
if(p.endsWith('/quote'))data={estimated_cost_brl:1};
if(p.endsWith('/capabilities'))data={model:'seedance',durations:[4,8],qualities:{draft:'720p',production:'720p'},motion_presets:['live'],ratios:['16:9','9:16','4:5','1:1'],skills:{}};
if(p.endsWith('/composition/exports')){exported=JSON.parse(route.request().postData());data={id:exported.request_id,status:'queued'};}
if(p.includes('/exports/')&&!p.endsWith('/content'))data={id:exported?.request_id,status:'queued'};
return route.fulfill({json:{success:true,data}});
});
await page.goto('http://studio.test/?client=1');await page.locator('[data-action="pick"][data-id="still1"]').click();
await page.waitForFunction(()=>document.querySelector('#mcStudioProjectAspect').value==='9:16');
await page.getByLabel('Formato do projeto',{exact:true}).selectOption('4:5');
await page.locator('[data-action="select"][data-id="still1"]').click();assert.equal(await page.getByLabel('Formato do projeto',{exact:true}).inputValue(),'4:5');
await page.locator('#mcStudioCollapseLibrary').click();assert.equal(await page.locator('#mcSwap').evaluate(el=>el.classList.contains('is-library-collapsed')),true);await page.locator('[data-studio-section="video"]').click();
await page.locator('[data-panel-tab="video"]').click();await page.locator('#mcCompositionAsset').selectOption('video:clip1');await page.locator('#mcCompositionAdd').click();
await page.locator('#mcCompositionAsset').selectOption('image:still1');await page.locator('#mcCompositionAdd').click();
assert.equal(await page.locator('[data-composition-item]').count(),2);
await page.locator('[data-compose-action="duplicate"]').click();assert.equal(await page.locator('[data-composition-item]').count(),3);
await page.locator('[data-compose-action="split"]').click();assert.equal(await page.locator('[data-composition-item]').count(),4);
await page.locator('[data-compose-key="transition"]').selectOption('fade');
await page.locator('[data-lib-tab="sound"]').click();await page.locator('[data-sound]').first().click();await page.locator('[data-sound]').nth(1).click();
assert.equal(await page.locator('.mc-composition-audio-lane').count(),2);
await page.locator('#mcCompositionCaptionFile').setInputFiles({name:'legendas.srt',mimeType:'application/x-subrip',buffer:Buffer.from('1\n00:00:00,200 --> 00:00:01,500\nOferta especial\n')});
assert.equal(await page.locator('[data-caption-key="text"]').inputValue(),'Oferta especial');
await page.locator('.mc-keyframes summary').first().click();
await page.locator('[data-keyframe-add]').first().click();
await page.locator('.mc-keyframes summary').first().click();
await page.locator('[data-keyframe-key="time"]').first().fill('1');await page.locator('[data-keyframe-key="time"]').first().dispatchEvent('change');
await page.locator('.mc-keyframes summary').first().click();
await page.locator('[data-keyframe-add]').first().click();
assert.equal(await page.locator('[data-keyframe-index]').count(),2);
await page.locator('#mcLivePlay').click();await page.waitForTimeout(350);
assert.ok(Number(await page.locator('#mcLiveSeek').inputValue())>0);await page.locator('#mcLivePlay').click();
await page.locator('summary').filter({hasText:/^Legendas$/}).click();
await page.locator('#mcCompositionTranscribe').click();
await page.waitForFunction(()=>document.querySelector('[data-caption-key="text"]').value==='Legenda automática');
await page.locator('#caduProcessing [data-close]').click();
await page.locator('#mcStudioExport').click();await page.locator('#caduProcessing[open]').waitFor();
await page.waitForFunction(()=>document.querySelector('#caduProcessingNotice').textContent.includes('pode fechar'));
assert.equal(exported.composition.items.length,4);assert.equal(exported.composition.items.at(-1).keyframes.length,2);assert.equal(exported.composition.audio.length,2);assert.equal(exported.composition.ratio,'4:5');
await page.screenshot({path:'tmp/studio-editor-check/processing.png',fullPage:true});
await page.locator('[data-close]').click();assert.equal(await page.locator('#caduProcessing').evaluate(el=>el.open),false);
await page.screenshot({path:'tmp/studio-editor-check/composition.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS actual aspect inference, explicit format, collapsible panels, 4-item assembly, split, duplicate, 2 audio tracks, SRT, automatic caption UI, keyframes, live playback, export payload, full-screen processing and background editing');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
