const {chromium}=require('/Users/apololira/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
let saved={},exported=null;
await page.route('http://studio.test/**',async route=>{
const url=new URL(route.request().url()),p=url.pathname;
if(p==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:fs.readFileSync('tmp/studio-editor-check/index.html','utf8')});
if(p.startsWith('/static/'))return route.fulfill({path:'aicentralv2'+p});
if(p==='/clip.mp4')return route.fulfill({path:'tmp/studio-editor-check/clip.mp4',contentType:'video/mp4'});
let data={};
if(p.endsWith('/swap/library'))data={items:url.searchParams.get('media')==='video'?[{id:'clip1',name:'Vídeo de teste',duration:3,video_url:'/clip.mp4'}]:[{id:'still1',name:'Criativo vertical',width:90,height:160,aspect_ratio:'16:9',image_url:'/static/images/canais/prime-video.svg'}]};
if(p.endsWith('/clips'))data={items:[]};
if(p.endsWith('/sounds'))data={items:JSON.parse(fs.readFileSync('aicentralv2/static/audio/studio/catalog.json')).map((row,index)=>index<2?{...row,duration:2,waveform:Array(10).fill(.5),waveform_levels:{overview:Array(10).fill(.5),medium:Array(20).fill(.5),detail:Array(30).fill(.5)}}:row)};
if(p.endsWith('/projects'))data=route.request().method()==='POST'?(saved=JSON.parse(route.request().postData()).document,{id:'project',revision:1,document:saved}):{items:[]};
if(p.endsWith('/projects/project'))data={id:'project',revision:2,document:(saved=JSON.parse(route.request().postData()).document)};
if(p.endsWith('/jobs'))data={items:[],exports:[]};
if(p.endsWith('/video-project'))data={project:{}};
if(p.endsWith('/inspect')||p.endsWith('/tasks'))data={has_audio:true,waveform:[],frames:[]};
if(p.endsWith('/tasks')&&JSON.parse(route.request().postData()).kind==='transcribe')data={id:'transcript',kind:'transcribe',status:'ready',result:{captions:[{start:.1,end:1,text:'Legenda automática'}],language:'pt'}};
if(p.endsWith('/quote'))data={estimated_cost_brl:1};
if(p.endsWith('/capabilities'))data={model:'seedance',durations:[4,8],qualities:{draft:'720p',production:'720p'},motion_presets:['live'],ratios:['16:9','9:16','4:5','1:1'],skills:{}};
if(p.endsWith('/composition/exports')){exported=JSON.parse(route.request().postData());data={id:exported.request_id,status:'queued'};}
if(p.includes('/exports/')&&!p.endsWith('/content'))data={id:exported?.request_id,status:'queued'};
return route.fulfill({json:{success:true,data}});
});
await page.goto('http://studio.test/?client=1');await page.locator('[data-action="pick"][data-id="still1"]').click();
await page.waitForFunction(()=>document.querySelector('#mcStudioProjectAspect').value==='9:16');
await page.getByLabel('Formato do projeto',{exact:true}).selectOption('4:5');
await page.locator('[data-action="select"][data-id="still1"]').click();assert.equal(await page.getByLabel('Formato do projeto',{exact:true}).inputValue(),'4:5');
await page.locator('#mcStudioCollapseLibrary').click();assert.equal(await page.locator('#mcSwap').evaluate(el=>el.classList.contains('is-library-collapsed')),true);await page.locator('[data-studio-section="video"]').click();
await page.locator('[data-panel-tab="video"]').click();await page.locator('#mcCompositionAsset').selectOption('video:clip1');await page.locator('#mcCompositionAdd').click();
await page.locator('#mcCompositionAsset').selectOption('image:still1');await page.locator('#mcCompositionAdd').click();
assert.equal(await page.locator('[data-composition-item]').count(),2);
await page.locator('[data-compose-action="duplicate"]').click();assert.equal(await page.locator('[data-composition-item]').count(),3);
await page.locator('[data-compose-action="split"]').click();assert.equal(await page.locator('[data-composition-item]').count(),4);
await page.locator('.mc-pro-clip').first().click();
await page.locator('[data-compose-key="transition"]').selectOption('fade');
assert.equal(await page.locator('[data-transition-index]').count(),1);
await page.locator('[data-lib-tab="sound"]').click();await page.locator('[data-sound]').first().click();await page.locator('[data-sound]').nth(1).click();
assert.equal(await page.locator('.mc-pro-audio').count(),2);
const widthBefore=await page.locator('.mc-pro-canvas').evaluate(el=>el.getBoundingClientRect().width),peaksBefore=Number(await page.locator('.mc-pro-audio').first().locator('.mc-pro-waveform svg').getAttribute('data-peaks'));await page.locator('#mcStudioZoom').fill('5');await page.locator('#mcStudioZoom').dispatchEvent('input');const widthAfter=await page.locator('.mc-pro-canvas').evaluate(el=>el.getBoundingClientRect().width),peaksAfter=Number(await page.locator('.mc-pro-audio').first().locator('.mc-pro-waveform svg').getAttribute('data-peaks'));assert.ok(widthAfter>widthBefore);assert.ok(peaksAfter>peaksBefore);
await page.locator('#mcTimelineSnap').click();assert.equal(await page.locator('#mcTimelineSnap').getAttribute('aria-pressed'),'false');await page.keyboard.press('n');assert.equal(await page.locator('#mcTimelineSnap').getAttribute('aria-pressed'),'true');
const transitionBefore=Number(await page.locator('[data-compose-key="transition_duration"]').inputValue()),transitionBox=await page.locator('[data-transition-index="0"]').boundingBox();await page.mouse.move(transitionBox.x+transitionBox.width-2,transitionBox.y+transitionBox.height/2);await page.mouse.down();await page.mouse.move(transitionBox.x+transitionBox.width+30,transitionBox.y+transitionBox.height/2);await page.mouse.up();assert.ok(Number(await page.locator('[data-compose-key="transition_duration"]').inputValue())>transitionBefore);
const trimBefore=Number(await page.locator('[data-compose-key="out"]').inputValue()),trimBox=await page.locator('.mc-pro-clip.is-selected [data-timeline-trim="out"]').boundingBox();await page.mouse.move(trimBox.x+trimBox.width/2,trimBox.y+trimBox.height/2);await page.mouse.down();await page.mouse.move(trimBox.x-30,trimBox.y+trimBox.height/2);await page.mouse.up();assert.ok(Number(await page.locator('[data-compose-key="out"]').inputValue())<trimBefore);
await page.locator('summary').filter({hasText:/^Áudio multifaixa$/}).click();
await page.locator('.mc-pro-audio').first().click();assert.equal(await page.locator('.mc-pro-audio.is-selected').count(),1);await page.locator('[data-audio-key="solo"]').first().check();assert.equal(await page.locator('.mc-pro-audio.is-solo').count(),1);
await page.locator('#mcLiveSeek').fill('0.5');await page.locator('#mcLiveSeek').dispatchEvent('input');await page.locator('[data-gain-add="0"]').click();assert.equal(await page.locator('.mc-pro-gain-point').count(),1);await page.locator('[data-gain-key="gain"]').fill('0.5');await page.locator('[data-gain-key="gain"]').dispatchEvent('change');await page.locator('[data-audio-sync="1"]').click();assert.equal(await page.locator('[data-audio-index="1"][data-audio-key="start"]').inputValue(),'0.5');await page.locator('[data-audio-restore-sync="1"]').click();assert.equal(await page.locator('[data-audio-index="1"][data-audio-key="start"]').inputValue(),'0');
await page.locator('[data-audio-split="0"]').click();assert.equal(await page.locator('.mc-pro-audio').count(),3);assert.equal(await page.locator('[data-gain-key="gain"]').nth(1).inputValue(),'0.5');await page.locator('[data-audio-remove="1"]').click();assert.equal(await page.locator('.mc-pro-audio').count(),2);
await page.locator('#mcCompositionCaptionFile').setInputFiles({name:'legendas.srt',mimeType:'application/x-subrip',buffer:Buffer.from('1\n00:00:00,200 --> 00:00:01,500\nOferta especial\n')});
assert.equal(await page.locator('[data-caption-key="text"]').inputValue(),'Oferta especial');
await page.locator('.mc-keyframes summary').first().click();
await page.locator('[data-keyframe-add]').first().click();
await page.locator('.mc-keyframes summary').first().click();
await page.locator('[data-keyframe-key="time"]').first().fill('1');await page.locator('[data-keyframe-key="time"]').first().dispatchEvent('change');
await page.locator('.mc-keyframes summary').first().click();
await page.locator('[data-keyframe-add]').first().click();
assert.equal(await page.locator('[data-keyframe-index]').count(),2);
await page.locator('#mcLivePlay').click();await page.waitForTimeout(350);
assert.ok(Number(await page.locator('#mcLiveSeek').inputValue())>0);await page.locator('#mcLivePlay').click();
await page.locator('summary').filter({hasText:/^Legendas$/}).click();
await page.locator('#mcCompositionTranscribe').click();
await page.waitForFunction(()=>document.querySelector('[data-caption-key="text"]').value==='Legenda automática');
await page.locator('#caduProcessing [data-close]').click();
await page.locator('summary').filter({hasText:/^Estilo das legendas/}).click();
await page.waitForSelector('[data-caption-preset="yellow"]');
assert.equal(await page.locator('[data-caption-preset]').count(),10);
await page.locator('[data-caption-preset="yellow"]').click();
await page.locator('[data-caption-style="font"]').selectOption('anton');
await page.locator('[data-caption-style="size"]').fill('6');await page.locator('[data-caption-style="size"]').dispatchEvent('change');
await page.locator('[data-caption-position=".14"]').click();
await page.locator('#mcLiveSeek').fill('0.5');await page.locator('#mcLiveSeek').dispatchEvent('input');
await page.locator('[data-caption-preset="classic"]').scrollIntoViewIfNeeded();
await page.screenshot({path:'tmp/studio-editor-check/caption-style-controls.png',fullPage:true});
await page.locator('#mcStudioExportFormat').selectOption('mp4');
await page.waitForFunction(()=>document.querySelector('#mcStudioExportFormat').getAttribute('aria-busy')==='true');
await page.waitForTimeout(100);
assert.equal(exported.composition.caption_style.font,'anton');assert.equal(exported.composition.caption_style.size,.06);assert.equal(exported.composition.caption_style.y,.14);
assert.equal(exported.composition.items.length,4);assert.equal(exported.composition.items[0].keyframes.length,2);assert.equal(exported.composition.audio.length,2);assert.equal(exported.composition.audio[0].solo,true);assert.equal(exported.composition.audio[0].gain_points[0].gain,.5);assert.equal(exported.composition.ratio,'4:5');
await page.screenshot({path:'tmp/studio-editor-check/processing.png',fullPage:true});
assert.equal(await page.locator('#caduProcessing').evaluate(el=>el.open),false);
await page.screenshot({path:'tmp/studio-editor-check/composition.png',fullPage:true});
await page.locator('.mc-pro-clip').first().click();await page.locator('#mcLiveSeek').fill('0.5');await page.locator('#mcLiveSeek').dispatchEvent('input');await page.locator('[data-compose-action="split"]').click();assert.equal(await page.locator('[data-composition-item]').count(),5);assert.ok((await page.locator('[data-composition-item]').first().getAttribute('title')).includes('0.50s'));const beforeAutoOut=await page.locator('[data-compose-key="out"]').inputValue();await page.locator('.mc-pro-audio').first().click();
await page.evaluate(()=>document.dispatchEvent(new CustomEvent('cadu:apply-autocut',{detail:{id:'clip1',autocut:{duration:3,cuts:[{in:.8,out:1.2,reason:'Pausa',confidence:1}],review:[],options:{mode:'moderate',transition:'fade',transition_duration:.1}}}})));
assert.equal(await page.locator('[data-cut-timeline]').count(),1);
assert.equal(await page.locator('[data-composition-item]').count(),5);
await page.locator('[data-cut-decision="0"][data-decision="accepted"]').click();
await page.locator('[data-apply-autocut]').click();
assert.equal(await page.locator('[data-composition-item]').count(),2);
await page.locator('[data-compose-key="voice"]').selectOption('warm');
await page.locator('[data-compose-key="voice_amount"]').fill('0.8');await page.locator('[data-compose-key="voice_amount"]').dispatchEvent('change');
assert.equal(await page.locator('[data-compose-key="voice"]').inputValue(),'warm');
await page.locator('[data-restore-all]').click();
assert.equal(await page.locator('[data-composition-item]').count(),5);assert.equal(await page.locator('.mc-pro-audio').count(),2);assert.equal(await page.locator('.mc-pro-audio.is-selected').count(),1);assert.equal(await page.locator('[data-caption-key="text"]').inputValue(),'Legenda automática');
assert.equal(await page.locator('[data-compose-key="out"]').inputValue(),beforeAutoOut);
await page.screenshot({path:'tmp/studio-editor-check/autocut-controls.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS timeline zoom/snap, trim and transition drag, audio split/sync/solo/envelope, captions, keyframes, preview, export and non-destructive smart cuts');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
