const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),id='11111111-1111-4111-8111-111111111111';
const config={nodes:[],edges:[]};
const flow={id,name:'Jornada de teste',status:'draft',draft_revision:1,allowed_host:'example.test',config};
const items=['/cases/a','/cases/b','/cases/c','/en/cases/a','/en/cases/b','/en/cases/c'].map((url,index)=>({id:String(index),canonical_url:'https://example.test'+url,title:'Página '+index,title_clean:'Página '+index,path_prefix:url,locale:url.startsWith('/en/')?'en':'pt',role:index%2?'content':'entry',template_id:'cases',template_pattern:'/cases/*'}));
for(let i=0;i<533;i++)items.push({id:String(i+6),canonical_url:'https://example.test/p/'+i,title:'Página extra '+i,title_clean:'Página extra '+i,path_prefix:'/p/'+i,locale:'pt',role:'none',template_id:null});
const summary={descobertas:539,validas:539,classificadas:6,sem_tipo:533,no_fluxo:0,excluidas:{duplicada:0}};
const html='<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="/static/cadu_connect/react/app.css"><link rel="stylesheet" href="/static/cadu_connect/react/untitled.css"></head><body><div id="cadu-reports-v1-root"></div><script type="module" src="/static/cadu_connect/react/app.js"></script></body></html>';
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname.startsWith('/static/')){const file=path.join(root,'aicentralv2',pathname);if(fs.existsSync(file)){res.setHeader('Content-Type',file.endsWith('.css')?'text/css':'text/javascript');return res.end(fs.readFileSync(file));}res.statusCode=404;return res.end();}res.setHeader('Content-Type','text/html');res.end(html);});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/connect/api/v2/reports/**',route=>{const pathname=new URL(route.request().url()).pathname;let data={};if(pathname.endsWith('/bootstrap'))data={ready:true,features:{flows_workspace_v2:true},client:{client_id:1,role:'admin',client_name:'Teste'},clients:[],accounts:[],campaigns:[],reports:[],link_tests:[],workspace_projects:[],csrf:'test'};else if(pathname.endsWith('/flow'))data={flows:[flow],activity:[],events:[],tags:[],steps:[],tag_urls:{},supertag_sites:[],canvas_nodes:[],canvas_edges:[]};else if(pathname.endsWith('/discoveries'))data={run:{status:'completed',created_at:'2026-09-30T12:00:00Z'},pages:items,catalog:items,summary};else if(pathname.endsWith('/readiness'))data={tracking_ready:true,issues:[]};return route.fulfill({json:data});});
 await page.goto(`http://127.0.0.1:${server.address().port}/connect/app/flows/${id}?client_id=1`);
 await page.getByText('539 páginas verificadas · 0 no fluxo').waitFor();
 assert.equal(await page.getByText('/cases/*',{exact:false}).count(),1);
 assert(await page.getByText('/cases/*').first().innerText().then(text=>text.includes('EN')&&text.includes('PT')));
 await page.getByRole('button',{name:'Agrupar no fluxo'}).click();
 assert.equal(await page.locator('.flow-catalog-group-preview li').count(),6);
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await page.getByRole('textbox',{name:'Buscar páginas'}).fill('/p/532');
 await page.getByText('Página extra 532',{exact:true}).waitFor();
 assert.equal(await page.getByText('Nenhuma página corresponde aos filtros.').count(),0);
 assert.deepEqual(errors,[]);console.log('M2 navegador: 539 páginas, grupo PT/EN único e busca aprovados');
}finally{await browser.close();server.close();}})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
