// Criar (página real): rascunho → direção → revisão → geração → resultado → erro, em 4 larguras.
const {chromium,ARTIFACTS}=require('./studio-browser.cjs');
const {execFileSync}=require('child_process');
const fs=require('fs'),assert=require('node:assert/strict');
execFileSync(fs.existsSync('.venv/bin/python')?'.venv/bin/python':'python3',['tests/frontend/render-studio-create-fixture.py'],{stdio:'inherit'});
const HTML=fs.readFileSync('tests/frontend/.fixtures/studio-create/index.html','utf8');
const STILL='/static/images/cadu/brand-icons/studio-192.png';
const projects=[{id:'p1',name:'Lançamento Verão',client_id:174,brand_name:'Centralcomm',brand_context:{name:'Centralcomm',palette:['#6D4AFF','#101923'],logo_url:STILL,assets:{logo:[STILL],logos:[{id:'l1',url:STILL,is_primary:true}]},readiness:{has_logo:true,has_palette:true}}}];
async function open(browser,width,{failImage=false}={}){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[],calls=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.__cls=0;window.__shifts=[];new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput){window.__cls+=e.value;window.__shifts.push({v:+e.value.toFixed(3),t:Math.round(e.startTime),src:(e.sources||[]).map(x=>{const n=x.node;return n&&n.nodeType===1?(n.id?'#'+n.id:n.tagName.toLowerCase()+'.'+String(n.className).split(' ')[0]):'?';}).join(',')});}}).observe({type:'layout-shift',buffered:true});});
  await page.route('https://cdnjs.cloudflare.com/**',route=>route.fulfill({contentType:'text/css',body:''}));
  await page.route('https://fonts.googleapis.com/**',route=>route.fulfill({contentType:'text/css',body:''}));
  await page.route('http://studio.test/**',async route=>{
    const req=route.request(),url=new URL(req.url()),path=url.pathname,method=req.method();
    if(path==='/')return route.fulfill({contentType:'text/html',body:HTML});
    if(path.startsWith('/static/'))return fs.existsSync('aicentralv2'+path)?route.fulfill({path:'aicentralv2'+path}):route.fulfill({status:404,body:''});
    const ok=data=>route.fulfill({json:{success:true,data}});
    if(method!=='GET')calls.push({path,body:req.postData()});
    if(path.endsWith('/project-contexts'))return ok({items:projects});
    if(path.endsWith('/studio/csrf'))return ok({token:'studio-token'});
    if(path.endsWith('/create/directions'))return ok({directions:[{title:'Fim de tarde na praia',summary:'Produto em destaque com luz dourada.',prompt:'Peça 4:5 com o produto em primeiro plano, luz de fim de tarde.',reference_plan:[]}],count:1});
    if(path.endsWith('/create/image'))return failImage?route.fulfill({status:502,json:{success:false,error:'O provedor de imagem não respondeu.',studio_phase:'image_provider'}}):ok({image_url:STILL,charged_credits:120,remaining_credits:500,title:'Fim de tarde na praia',aspect_ratio:'4:5'});
    if(path==='/workspace/api/creditos/resumo')return route.fulfill({json:{configured:true,monthly:1000,available:640}});
    return ok({items:[],runs:[],personal_assets:[]});
  });
  await page.goto('http://studio.test/');
  await page.locator('#studioV2').waitFor();
  await page.waitForFunction(()=>!document.querySelector('#mcCaduProject')?.disabled);
  return {page,errors,calls};
}
const noOverflow=page=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);
(async()=>{
  const browser=await chromium.launch({headless:true});
  const report=[];
  for(const width of [1440,1024,768,390]){
    const {page,errors,calls}=await open(browser,width);
    assert.equal(await page.locator('#studioV2').getAttribute('data-state'),'draft');
    assert.ok(await noOverflow(page),`rascunho sem rolagem horizontal em ${width}px`);
    await page.screenshot({path:`${ARTIFACTS}/create-${width}-draft.png`});
    await page.locator('#promptInput').fill('Peça de verão para o feed com o produto em destaque e luz de fim de tarde.');
    await page.locator('#promptForm button[type=submit]').click();
    await page.locator('#resultsView').waitFor({state:'visible',timeout:30000});
    assert.equal(await page.locator('.results-grid .result-card').count(),1);
    await page.locator('.result-card .result-video').waitFor();
    await page.locator('.result-card .result-video').click({trial:true,timeout:5000});
    await page.locator('.result-card .result-edit').click({trial:true,timeout:5000});
    assert.ok(await noOverflow(page),`resultado sem rolagem horizontal em ${width}px`);
    await page.screenshot({path:`${ARTIFACTS}/create-${width}-results.png`,fullPage:true});
    const overlap=await page.evaluate(()=>{const header=document.getElementById('mcCaduBar').getBoundingClientRect();const nav=document.querySelector('.csu-navbar__nav').getBoundingClientRect();const toolbar=document.querySelector('.canvas-toolbar').getBoundingClientRect();return {navBottom:Math.round(nav.bottom),headerBottom:Math.round(header.bottom),toolbarTop:Math.round(toolbar.top),scrollY:Math.round(scrollY),headerPos:getComputedStyle(document.getElementById('mcCaduBar')).position,toolbarPos:getComputedStyle(document.querySelector('.canvas-toolbar')).position};});
    if(process.env.CLS_DEBUG)console.log(width,'overlap',JSON.stringify(overlap),JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('*')].filter(n=>n.scrollTop>0).map(n=>(n.id?'#'+n.id:n.tagName.toLowerCase()+'.'+String(n.className).split(' ')[0])+':'+n.scrollTop+':'+getComputedStyle(n).overflowY))));
    assert.ok(overlap.navBottom<=overlap.headerBottom+1,`navbar transborda o cabeçalho em ${width}px: ${JSON.stringify(overlap)}`);
    assert.ok(overlap.toolbarTop>=overlap.headerBottom-1,`barra do canvas sob a navbar em ${width}px: ${JSON.stringify(overlap)}`);
    const directions=JSON.parse(calls.find(c=>c.path.endsWith('/create/directions')).body);
    assert.match(directions.prompt,/luz de fim de tarde/);
    const image=JSON.parse(calls.find(c=>c.path.endsWith('/create/image')).body);
    assert.equal(image.direction_approved,true);
    assert.deepEqual([image.width,image.height],[1080,1350]);
    const cls=await page.evaluate(()=>window.__cls);
    report.push(`${width}px CLS=${cls.toFixed(3)}`);
    assert.ok(cls<0.1,`layout instável em ${width}px: CLS ${cls.toFixed(3)} (limite 0,1)`);
    if(process.env.CLS_DEBUG&&cls>0.1)console.log(width,JSON.stringify(await page.evaluate(()=>window.__shifts)));
    assert.deepEqual(errors,[],`erros de JS em ${width}px`);
    await page.close();
  }
  const manual=await open(browser,1440);
  await manual.page.locator('label.prompt-approve').click();
  assert.equal(await manual.page.locator('#autoApproveDirection').isChecked(),false);
  await manual.page.locator('#promptInput').fill('Peça de verão para o feed com o produto em destaque.');
  await manual.page.locator('#promptForm button[type=submit]').click();
  await manual.page.locator('#directionCard').waitFor({state:'visible',timeout:30000});
  assert.equal(manual.calls.filter(c=>c.path.endsWith('/create/image')).length,0,'nada é gerado antes da aprovação');
  await manual.page.locator('#approveDirection').waitFor({state:'visible'});
  await manual.page.locator('#approveDirection').click();
  await manual.page.locator('#resultsView').waitFor({state:'visible',timeout:30000});
  assert.equal(manual.calls.filter(c=>c.path.endsWith('/create/image')).length,1);
  assert.deepEqual(manual.errors,[]);
  await manual.page.close();
  const failing=await open(browser,1440,{failImage:true});
  await failing.page.locator('#promptInput').fill('Peça de verão para o feed com o produto em destaque.');
  await failing.page.locator('#promptForm button[type=submit]').click();
  await failing.page.locator('#composerFeedback').waitFor({state:'visible',timeout:30000});
  assert.match(await failing.page.locator('#composerFeedbackText').textContent(),/provedor de imagem/);
  assert.equal(await failing.page.locator('#studioV2').getAttribute('data-state'),'review_error');
  await failing.page.getByRole('button',{name:'Tentar novamente'}).waitFor();
  assert.equal(await failing.page.locator('#promptInput').inputValue(),'Peça de verão para o feed com o produto em destaque.','o briefing continua na tela depois do erro');
  await failing.page.screenshot({path:`${ARTIFACTS}/create-1440-error.png`});
  console.log('CLS por largura:',report.join(' · '));
  console.log('PASS Criar: rascunho → direção → (revisão manual) → geração → resultado em 1440/1024/768/390px sem rolagem horizontal, erro preserva o briefing, sem erros de JS');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
