// Super Tag installed through Google Tag Manager: the custom HTML generated by the panel (reports_supertag._supertag_gtm_snippet)
// is injected the way GTM does it (parsed, each <script> recreated so it runs) and the tag must still find its site id
// (document.currentScript of a dynamically inserted script, or ?id= in its URL) and send the page_view. Source and minified file.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

const root = path.resolve(__dirname, '../..');
const base = 'https://reports.example.test/connect/public/supertag/v1/gtm-ui';
const cors = {'Access-Control-Allow-Origin': 'https://example.test', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type'};

/** The exact HTML the panel shows for GTM, produced by the backend. */
function gtmSnippet() {
  const python = process.env.PYTHON || path.join(root, '.venv/bin/python');
  const code = [
    'from flask import Flask',
    'from aicentralv2.cadu_connect import reports_supertag',
    "app = Flask('t'); app.config['CONNECT_URL'] = 'https://reports.example.test'",
    'with app.test_request_context("/"):',
    "    print(reports_supertag._supertag_gtm_snippet({'public_id': 'gtm-ui', 'label': 'Loja', 'allowed_host': 'example.test'}), end='')",
  ].join('\n');
  return execFileSync(python, ['-c', code], {cwd: root, encoding: 'utf8'});
}

/** A stand-in for gtm.js: custom HTML tags are parsed and every <script> is recreated (attributes and text) so it executes. */
const FAKE_GTM = `(function inject() {
  if (!document.body) { document.addEventListener('DOMContentLoaded', inject); return; }
  var holder = document.createElement('div');
  holder.innerHTML = window.__customHtml;
  Array.prototype.slice.call(holder.childNodes).forEach(function (node) {
    if (node.nodeName !== 'SCRIPT') { document.body.appendChild(node.cloneNode(true)); return; }
    var copy = document.createElement('script');
    for (var i = 0; i < node.attributes.length; i++) copy.setAttribute(node.attributes[i].name, node.attributes[i].value);
    copy.text = node.text;
    document.body.appendChild(copy);
  });
})();`;

async function run(browser, file, customHtml) {
  const page = await browser.newPage();
  const events = [], errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const html = `<!doctype html><html><head><meta charset="utf-8"><script>window.__customHtml = ${JSON.stringify(customHtml).replace(/</g, '\\u003c')};</script>
    <script async src="https://www.googletagmanager.com/gtm.js?id=GTM-TESTE"></script></head><body><main>Loja</main></body></html>`;
  await page.route('https://example.test/**', route => route.fulfill({contentType: 'text/html', body: html}));
  await page.route('https://www.googletagmanager.com/**', route => route.fulfill({contentType: 'text/javascript', body: FAKE_GTM}));
  await page.route(/https:\/\/reports\.example\.test\/v1\/supertag\.js(\?.*)?$/, route => route.fulfill({contentType: 'text/javascript',
    body: fs.readFileSync(path.join(root, 'aicentralv2/static/cadu_connect', file), 'utf8')}));
  await page.route(`${base}/config.json`, route => route.fulfill({headers: cors, json: {site_id: 'gtm-ui', config_version: 1,
    visibility_enabled: false, audience_days: 90, form_capture: {enabled: false, fields: []}}}));
  await page.route(`${base}/collect`, route => {
    if (route.request().method() === 'OPTIONS') return route.fulfill({status: 204, headers: cors});
    JSON.parse(route.request().postData()).events.forEach(item => events.push(item));
    return route.fulfill({status: 202, headers: cors, json: {accepted: 1}});
  });
  await page.goto('https://example.test/produtos');
  await page.waitForFunction(() => window.CaduSuperTag && window.CaduSuperTag.getSessionId(), null, {timeout: 5000});
  await page.evaluate(() => window.dispatchEvent(new Event('pagehide')));
  for (let i = 0; i < 50 && !events.some(item => item.kind === 'page_view'); i++) await page.waitForTimeout(100);
  const comments = await page.evaluate(() => {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_COMMENT);
    const found = [];
    while (walker.nextNode()) found.push(walker.currentNode.nodeValue.trim());
    return found;
  });
  await page.close();
  assert.deepEqual(errors, [], `${file}: sem erros de JavaScript`);
  return {events, comments};
}

async function main() {
  const snippet = gtmSnippet();
  assert.match(snippet, /^<!-- Cadu Super Tag · Loja \(example\.test\) -->\n<script>/, 'snippet GTM começa com o comentário nomeado');
  assert.match(snippet, /<\/script>\n<!-- End Cadu Super Tag -->$/, 'snippet GTM termina com o comentário de fim');
  // A loader that drops the data attribute: the id still comes from ?id= in the URL.
  const withoutAttribute = snippet.replace(/\n\s*s\.setAttribute\('data-cadu-site', 'gtm-ui'\);/, '');
  assert.notEqual(withoutAttribute, snippet);
  const browser = await chromium.launch({headless: true, ...(process.env.CHROME_PATH ? {executablePath: process.env.CHROME_PATH} : {})});
  try {
    for (const file of ['cadu-supertag-v1.js', 'cadu-supertag-v1.min.js']) {
      const {events, comments} = await run(browser, file, snippet);
      const views = events.filter(item => item.kind === 'page_view');
      assert.deepEqual(views.map(item => item.path), ['/produtos'], `${file}: page_view sai pela tag injetada pelo GTM`);
      assert.deepEqual(comments, ['Cadu Super Tag · Loja (example.test)', 'End Cadu Super Tag'], `${file}: comentários preservados`);
      const fallback = await run(browser, file, withoutAttribute);
      assert.deepEqual(fallback.events.filter(item => item.kind === 'page_view').map(item => item.path), ['/produtos'],
        `${file}: sem data-cadu-site, o id vem de ?id= na URL do script`);
    }
  } finally {
    await browser.close();
  }
  process.stdout.write('Super Tag via Google Tag Manager: snippet com comentários, tag injetada e page_view enviados (fonte e minificado).\n');
}

main().catch(error => { console.error(error); process.exit(1); });
