import React,{useMemo,useState} from 'react';
import {SearchLg, Plus, MarkerPin01} from '@untitledui/icons';
import {ReportsActionButton as Button} from './ReportsActionButton.jsx';
const labels={entry:'Entrada',institutional:'Institucional',offer:'Oferta',content:'Conteúdo',intent:'Intenção',form:'Formulário',conversion:'Conversão',checkout:'Checkout',legal:'Legal',error:'Erro',none:'Sem papel'};
export function FlowCatalog({items=[],nodes=[],onAdd,onAddGroup,onLocate,disabled,onClassify,suggestions={},classifying,onAcceptSuggestion}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState([]);
 const rows=useMemo(()=>items.map(page=>({...page,node:nodes.find(n=>n.discoveryPageId===String(page.id)||(n.path===page.path_prefix&&n.type==='page'&&(!n.host||n.host===page.page_host)))})).filter(page=>`${page.title_clean} ${page.path_prefix}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='mapped'&&page.node||page.role===filter)),[items,nodes,query,filter]);
 const groups=Object.groupBy?Object.groupBy(rows,p=>p.role):rows.reduce((out,p)=>({...out,[p.role]:[...(out[p.role]||[]),p]}),{});
 return <div className="flow-catalog"><label className="flow-catalog-search"><SearchLg size={16}/><input aria-label="Buscar páginas" placeholder="Buscar página ou URL" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="flow-catalog-filters">{[['all','Todos'],['mapped','No fluxo'],['conversion','Conversão'],['intent','Intenção'],['none','Sem papel']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><small>{items.length} páginas · {items.filter(p=>p.role!=='none').length} classificadas por regras</small>{selected.length>1&&<Button disabled={disabled} onClick={()=>{onAddGroup(items.filter(p=>selected.includes(String(p.id))));setSelected([]);}}>Agrupar {selected.length} páginas</Button>}{Object.entries(groups).map(([role,pages])=><details key={role} open><summary>{labels[role]||role} · {pages.length}</summary>{Array.from(new Set(pages.map(p=>p.template_id).filter(Boolean))).map(id=>{const members=pages.filter(p=>p.template_id===id);return <details key={id}><summary>{members[0].template_pattern} · {members.length} páginas</summary><Button disabled={disabled} onClick={()=>onAddGroup(members)}>Adicionar como grupo</Button>{members.map(p=><p key={p.id}>{p.title_clean}</p>)}</details>;})}{pages.filter(p=>!p.template_id).map(page=><div className="flow-catalog-row" key={page.canonical_url} title={`${page.title}\n${page.canonical_url}\n${page.evidence_text}`}><input type="checkbox" aria-label={`Selecionar ${page.title_clean}`} checked={selected.includes(String(page.id))} onChange={e=>setSelected(ids=>e.target.checked?[...ids,String(page.id)]:ids.filter(id=>id!==String(page.id)))}/><span><strong>{page.title_clean}</strong><small>{page.path_prefix}</small></span><Button color="tertiary" disabled={disabled} aria-label={page.node?'Localizar etapa':'Adicionar etapa'} onClick={()=>page.node?onLocate(page.node.id):onAdd(page)}>{page.node?<MarkerPin01 size={16}/>:<Plus size={16}/>}</Button>{page.role==='none'&&onClassify&&<details><summary aria-label="Revisar papel da página">⋯</summary><Button disabled={disabled||Boolean(classifying)} onClick={()=>onClassify(page)}>{classifying===String(page.id)?'Analisando…':'Sugerir papel com IA'}</Button><small>Consome 1 análise · limite de 50 por cliente/24 h.</small>{suggestions[page.id]&&<><p>Sugestão de IA: {suggestions[page.id].suggestion.role} · requer revisão</p>{suggestions[page.id].suggestion.role!=='none'&&<Button disabled={disabled} onClick={()=>onAcceptSuggestion(page,suggestions[page.id])}>Aceitar papel sugerido</Button>}</>}</details>}</div>)}</details>)}{!rows.length&&<p>Nenhuma página corresponde aos filtros.</p>}</div>;
}
