import {ReportsPanelShell} from './ReportsPanelShell.jsx';
import React,{useEffect,useMemo,useState,useRef} from 'react';
import {ReportsActionButton as Button} from './ReportsActionButton.jsx';
export function FlowStudioAssist({suggestionToggle=0,config,catalog=[],onChange,onLocate,onOrganize,onBuild,onShowReturns,onAddPage}){
 const dialog=useRef(null);
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[suggestionsOpen,setSuggestionsOpen]=useState(false);
 useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
 useEffect(()=>{const handler=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v);}if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{if(suggestionToggle)setSuggestionsOpen(v=>!v);},[suggestionToggle]);
 const suggestions=useMemo(()=>catalog.flatMap(page=>{const node=config.nodes.find(n=>n.path===page.path_prefix&&(!n.host||n.host===page.page_host));if(!node||page.role!=='conversion'||node.type==='conversion')return [];return [{id:`conversion:${node.id}`,nodeId:node.id,message:`${page.path_prefix} parece uma página de confirmação. Marcar como conversão?`,evidence:page.evidence_text}];}).filter(item=>!(config.dismissedSuggestions||[]).includes(item.id)),[catalog,config]);
 return <><div className="flow-assist-actions"><Button aria-label="Buscar e executar comandos" onClick={()=>setOpen(true)}>Buscar comandos <kbd>{/Mac|iPhone|iPad/.test(navigator.platform)?'⌘K':'Ctrl K'}</kbd></Button></div>{suggestionsOpen&&<ReportsPanelShell className="flow-assist-panel" title="Sugestões" onClose={()=>setSuggestionsOpen(false)}>{suggestions.length?suggestions.map(item=><section key={item.id}><p>{item.message}</p><small>Regra · {item.evidence}</small><div><Button onClick={()=>onChange(current=>({...current,nodes:current.nodes.map(n=>n.id===item.nodeId?{...n,type:'conversion',kind:'conversion.generic',stage:'conversion',manuallyEdited:true}:n)}))}>Aplicar</Button><Button onClick={()=>onChange(current=>({...current,dismissedSuggestions:[...(current.dismissedSuggestions||[]),item.id]}))}>Dispensar</Button></div></section>):<p>Sem novas sugestões com a evidência disponível.</p>}</ReportsPanelShell>}{open&&<dialog ref={dialog} onCancel={()=>setOpen(false)} className="flow-command-dialog" aria-label="Comandos do fluxo"><header><input autoFocus aria-label="Buscar comando ou nó" placeholder="Buscar nó ou comando…" value={query} onChange={e=>setQuery(e.target.value)}/><Button onClick={()=>setOpen(false)}>Fechar</Button></header>{[['Organizar por etapas',onOrganize],['Montar a partir do site',onBuild],['Mostrar/ocultar retornos',onShowReturns],...catalog.filter(p=>!p.in_flow_node_id).map(p=>[`Adicionar ${p.title_clean}`,()=>onAddPage?.(p)]),...config.nodes.map(n=>[n.title,()=>onLocate(n.id)])].filter(([title])=>title.toLowerCase().includes(query.toLowerCase())).slice(0,30).map(([title,action],index)=><Button key={index} onClick={()=>{action?.();setOpen(false);}}>{title}</Button>)}</dialog>}</>;
}
