import {ReportsPanelShell} from './ReportsPanelShell.jsx';
import React,{useEffect,useState} from 'react';
import {ReportsActionButton as Button} from './ReportsActionButton.jsx';
import {ReportsNativeSelect} from './ReportsNativeSelect.jsx';
import {applyBlueprint,previewBlueprint} from './flowBlueprintApply.js';
export {applyBlueprint} from './flowBlueprintApply.js';
export function FlowBlueprint({flowId,clientId,csrf,domain,config,onApply,onClose,onPreview}){
 const storageKey=`reports-blueprint:${clientId}:${flowId}`;
 const [job,setJob]=useState(()=>{try{return JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch{return null;}}),[goal,setGoal]=useState('auto'),[useAi,setUseAi]=useState(false),[useObserved,setUseObserved]=useState(true),[includeMedia,setIncludeMedia]=useState(true),[accepted,setAccepted]=useState([]),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[starting,setStarting]=useState(false);
 const call=async(path,method='GET',body)=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(`/connect/api/v2/reports/flow/${path}?client_id=${clientId}`,{method,signal:controller.signal,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body?{body:JSON.stringify({...body,client_id:clientId})}:{})});const result=await r.json();if(!r.ok)throw new Error(result.description||result.error||'Não foi possível montar o fluxo.');return result;}finally{clearTimeout(timer);}};
 useEffect(()=>{if(!job?.job_id||['ready','failed','cancelled'].includes(job.status))return;let active=true,timer;const poll=async()=>{try{const value=await call(`blueprint-jobs/${job.job_id}`);if(!active)return;setJob(value);sessionStorage.setItem(storageKey,JSON.stringify({job_id:value.job_id,status:value.status==='ready'?'running':value.status}));if(value.status==='ready')setAccepted(value.result.nodes.map(n=>n.id));}catch(e){if(active)setError(e.message);}if(active)timer=setTimeout(poll,2000);};timer=setTimeout(poll,500);return()=>{active=false;clearTimeout(timer);};},[job?.job_id,job?.status]);
 useEffect(()=>{onPreview?.(job?.status==='ready'?previewBlueprint(job.result,accepted):{nodes:[],edges:[]});return()=>onPreview?.({nodes:[],edges:[]});},[job?.status,accepted]);
 const start=async()=>{setStarting(true);setError('');setConfirmed(false);try{const value=await call(`flows/${flowId}/blueprint`,'POST',{domain,goal,use_observed:useObserved,include_media:includeMedia,use_ai:useAi});setJob(value);sessionStorage.setItem(storageKey,JSON.stringify(value));}catch(e){setError(e.message);}finally{setStarting(false);}};
 return <ReportsPanelShell className="flow-blueprint-panel" title="Montar a partir do site" description={domain} onClose={onClose} footer={job?.status==='ready'?<Button color="primary" disabled={!confirmed||!accepted.length} onClick={()=>{try{onApply(applyBlueprint(config,job.result,accepted));sessionStorage.removeItem(storageKey);onClose();}catch(e){setError(e.message);}}}>Aplicar proposta</Button>:null}>{error&&<p role="alert">{error}</p>}{!job||['failed','cancelled'].includes(job.status)?<><label>Objetivo<ReportsNativeSelect value={goal} onChange={e=>setGoal(e.target.value)}>{[['auto','Detectar automaticamente'],['leads','Gerar leads'],['sale','Venda'],['appointment','Agendamento'],['whatsapp','WhatsApp']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</ReportsNativeSelect></label><label><input type="checkbox" checked={useObserved} onChange={e=>setUseObserved(e.target.checked)}/>Usar navegação observada</label><label><input type="checkbox" checked={includeMedia} onChange={e=>setIncludeMedia(e.target.checked)}/>Incluir contas de mídia</label><label><input type="checkbox" checked={useAi} onChange={e=>setUseAi(e.target.checked)}/>Classificar páginas ambíguas com IA</label><p>{useAi?'Até 20 análises nesta montagem, dentro da cota de 50 por cliente/24 h.':'Sem consumo de análises de IA.'} Revise a proposta antes de aplicar.</p>{job?.message&&<p role="alert">{job.message}</p>}<Button color="primary" disabled={starting} onClick={start}>{starting?'Iniciando…':'Analisar site'}</Button></>:job.status==='ready'?<><p>{job.result.nodes.length} etapas propostas · {job.result.groups?.length||0} grupos · {job.result.edges.length} conexões</p><p>{config.nodes.filter(n=>n.origin!=='blueprint'||n.manuallyEdited||n.locked).length} etapas manuais ou fixadas serão preservadas. {job.result.ai_analyses||0} análises de IA.</p><Button onClick={()=>setAccepted(job.result.nodes.map(n=>n.id))}>Selecionar todas</Button>{job.result.warnings.map(w=><p key={w}>{w}</p>)}{job.result.nodes.map(node=><label className="flow-blueprint-choice" key={node.id}><input type="checkbox" checked={accepted.includes(node.id)} onChange={e=>setAccepted(ids=>e.target.checked?[...ids,node.id]:ids.filter(id=>id!==node.id))}/><span>{node.title}<small>{node.path} · {node.evidence}</small></span></label>)}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Revisei as etapas e o objetivo proposto.</label></>:<><p role="status">{job.steps?.[job.step]||'Aguardando processamento'}…</p><p>Você pode fechar este painel e continuar editando.</p><Button onClick={async()=>{try{setJob(await call(`blueprint-jobs/${job.job_id}`,'DELETE'));}catch(e){setError(e.message);}}}>Cancelar montagem</Button></>}</ReportsPanelShell>;
}
