import {ReportsRelationships} from './ReportsRelationships.jsx';
import React,{useState} from 'react';
import {FlowCanvas} from './FlowCanvas.jsx';
import {ReportsActionButton as Button} from './ReportsActionButton.jsx';
import {ReportsFieldInput} from './ReportsFieldInput.jsx';
import {ReportsNativeSelect} from './ReportsNativeSelect.jsx';
import {plural} from './flowFeedback.js';
export function FlowLibrary({data,flows,onOpen,onCreate,readOnly,createPanel}) {
  const [query,setQuery]=useState(''),[status,setStatus]=useState('all');
  const visible=flows.filter(f=>(status==='all'||f.status===status)&&`${f.name} ${f.allowed_host}`.toLowerCase().includes(query.toLowerCase()));
  return <div className={`flow-library-layout${createPanel?' has-create-panel':''}`}><section className="flow-library"><header><div><h2>Fluxos existentes</h2><p>Organize jornadas e acompanhe resultados por site.</p></div>{!createPanel&&!readOnly&&<Button color="primary" onClick={onCreate}>Criar fluxo</Button>}</header><div className="flow-library-tools"><ReportsFieldInput type="search" aria-label="Buscar fluxo" placeholder="Buscar nome ou domínio" value={query} onChange={e=>setQuery(e.target.value)}/><ReportsNativeSelect aria-label="Estado do fluxo" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os fluxos</option><option value="published">Publicados</option><option value="draft">Rascunhos</option></ReportsNativeSelect><small>{plural(visible.length,'fluxo','fluxos')}</small></div><div className="flow-library-grid">{visible.map(f=><article key={f.id}><div className="flow-library-preview" aria-hidden="true"><FlowCanvas config={f.config||{nodes:[],edges:[]}} readOnly setConfig={()=>{}} setSelectedNodeId={()=>{}} fitOnMount/></div><div className="flow-library-description"><h3>{f.name}</h3><p>{f.allowed_host}</p><small>{f.status==='published'?`Publicado · v${f.published_revision}`:'Rascunho'}{f.customer_id&&data?.customers?.find(c=>String(c.id)===String(f.customer_id))?` · ${data.customers.find(c=>String(c.id)===String(f.customer_id)).name}`:''}{f.campaign_id&&data?.campaigns?.find(c=>String(c.id)===String(f.campaign_id))?` · ${data.campaigns.find(c=>String(c.id)===String(f.campaign_id)).name}`:''}</small><div>{!readOnly&&<Button onClick={()=>onOpen(f,'edit')}>Editar</Button>}<Button color="secondary" onClick={()=>onOpen(f,'monitor')}>Monitorar</Button>{data&&<ReportsRelationships data={data} kind="flow" id={f.id} name={f.name} flow={f}/>}</div></div></article>)}</div>{!visible.length&&<p role="status">{query||status!=='all'?'Nenhum fluxo corresponde aos filtros.':'Crie seu primeiro fluxo para organizar as páginas do site.'}</p>}</section>{createPanel&&<aside className="flow-library-create">{createPanel}</aside>}</div>;
}
