import React,{useRef,useState} from 'react';
import {ReportsActionButton as Button} from './ReportsActionButton.jsx';
import {ReportsDrawer} from './ReportsDrawer.jsx';
import {ReportsNativeSelect} from './ReportsNativeSelect.jsx';
import {ReportsFieldInput} from './ReportsFieldInput.jsx';
export function ReportsRelationships({data,kind,id,name,flow}) {
  const [open,setOpen]=useState(false),[items,setItems]=useState(null),[links,setLinks]=useState([]),[grants,setGrants]=useState([]),[ref,setRef]=useState(''),[email,setEmail]=useState(''),[projectName,setProjectName]=useState(''),[customer,setCustomer]=useState(''),[customerLoaded,setCustomerLoaded]=useState(false),[flowCustomer,setFlowCustomer]=useState(String(flow?.customer_id||'')),[flowCampaign,setFlowCampaign]=useState(String(flow?.campaign_id||'')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const projectRequests=useRef(new Map());
  const projectKey=()=>{const key=JSON.stringify([data.client.client_id,kind,id,projectName]);if(!projectRequests.current.has(key))projectRequests.current.set(key,crypto.randomUUID());return projectRequests.current.get(key);};
  const base=`/connect/api/v2/reports`,scope=`client_id=${data.client.client_id}`;
  const call=async(path,method='GET',payload={})=>{const r=await fetch(`${base}${path}?${scope}`,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':data.csrf},...(method!=='GET'?{body:JSON.stringify({...payload,client_id:data.client.client_id})}:{})});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.description||result.error||`Falha HTTP ${r.status}`);return result;};
  const run=async(action)=>{setBusy(true);setError('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const target=kind==='customer'?`/customers/${id}/brands`:`/workspace/${kind}/${id}`;
  const loadWorkspace=()=>run(async()=>{const catalog=await call('/workspace/catalog');setItems(catalog.items.filter(i=>i.kind===(kind==='customer'?'brand':'project')));const result=await call(target);setLinks(result.links||result.brands||[]);});
  const loadGrants=()=>run(async()=>setGrants((await call(`/${kind}/${id}/grants`)).grants));
  return <><Button color="tertiary" onClick={()=>setOpen(true)}>Vínculos{['site','flow'].includes(kind)?' e acesso':''}</Button><ReportsDrawer open={open} onOpenChange={setOpen} onDiscard={()=>{setRef('');setEmail('');setProjectName('');setError('');setCustomer('');setCustomerLoaded(false);}} title={name||'Vínculos'} description="Integrações opcionais. Seu recurso continua funcionando sem Workspace.">
    {error&&<p role="alert" className="reports-error">{error}</p>}
    {['site','campaign','account'].includes(kind)&&<section><h3>Cliente / anunciante</h3><Button disabled={busy} onClick={()=>run(async()=>{const r=await call(`/${kind}/${id}/customer`);setCustomer(String(r.customer_id||''));setCustomerLoaded(true);})}>Consultar associação</Button>{customerLoaded&&<form className="reports-form" onSubmit={e=>{e.preventDefault();run(()=>call(`/${kind}/${id}/customer`,'PATCH',{customer_id:customer||null}));}}><label>Cliente<ReportsNativeSelect value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Operação própria</option>{(data.customers||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</ReportsNativeSelect></label><Button disabled={busy||data.client.role==='viewer'} type="submit">Salvar associação</Button></form>}</section>}
    {kind==='flow'&&flow&&<section><h3>Contexto do fluxo</h3><p>O anunciante e a campanha são opcionais. O fluxo continua no Reports deste cliente.</p><form className="reports-form" onSubmit={e=>{e.preventDefault();run(async()=>{await call(`/flow/flows/${id}/associations`,'PATCH',{customer_id:flowCustomer||null,campaign_id:flowCampaign||null});window.location.reload();});}}><label>Cliente / anunciante<ReportsNativeSelect value={flowCustomer} onChange={e=>{setFlowCustomer(e.target.value);setFlowCampaign('');}}><option value="">Sem anunciante</option>{(data.customers||[]).filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</ReportsNativeSelect></label><label>Campanha<ReportsNativeSelect value={flowCampaign} onChange={e=>setFlowCampaign(e.target.value)}><option value="">Sem campanha</option>{(data.campaigns||[]).filter(c=>!flowCustomer||String(c.customer_id)===flowCustomer).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</ReportsNativeSelect></label><Button type="submit" disabled={busy||data.client.role==='viewer'}>Salvar vínculo</Button></form></section>}
    {kind!=='account'&&<section><h3>Workspace</h3>{items===null?<Button disabled={busy} onClick={loadWorkspace}>Consultar {kind==='customer'?'marcas':'projetos'} acessíveis</Button>:<><form className="reports-form" onSubmit={e=>{e.preventDefault();run(async()=>{await call(target,'POST',{[kind==='customer'?'brand_ref':'project_ref']:ref});const result=await call(target);setLinks(result.links||result.brands||[]);});}}><label>{kind==='customer'?'Marca':'Projeto'}<ReportsNativeSelect required value={ref} onChange={e=>setRef(e.target.value)}><option value="">Selecione</option>{items.map(i=><option key={i.ref} value={i.ref}>{i.name}</option>)}</ReportsNativeSelect></label><Button type="submit" disabled={busy||!ref||data.client.role==='viewer'}>Vincular</Button></form>{links.length?links.map(i=><p key={i.ref}>{i.name} <Button disabled={busy||data.client.role==='viewer'} onClick={()=>run(async()=>{await call(target,'DELETE',{[kind==='customer'?'brand_ref':'project_ref']:i.ref});setLinks(l=>l.filter(x=>x.ref!==i.ref));})}>Desvincular</Button></p>):<p>Nenhum vínculo.</p>}{['site','flow'].includes(kind)&&<form className="reports-form" onSubmit={e=>{e.preventDefault();run(async()=>{await call(`${target}/create-project`,'POST',{name:projectName,idempotency_key:projectKey()});const result=await call(target);setLinks(result.links||[]);setProjectName('');});}}><label>Novo projeto no Workspace<ReportsFieldInput required maxLength={80} value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><Button disabled={busy||data.client.role==='viewer'} type="submit">Criar e vincular</Button></form>}</>}</section>}
    {['site','flow'].includes(kind)&&data.client.role==='admin'&&<section><h3>Compartilhar monitoramento</h3><p>Conceda visualização a um usuário cadastrado pelo e-mail.</p><Button disabled={busy} onClick={loadGrants}>Consultar acessos</Button><form className="reports-form" onSubmit={e=>{e.preventDefault();run(async()=>{await call(`/${kind}/${id}/grants`,'POST',{email});setGrants((await call(`/${kind}/${id}/grants`)).grants);setEmail('');});}}><label>E-mail<ReportsFieldInput required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button disabled={busy} type="submit">Compartilhar</Button></form>{grants.map(g=><p key={g.user_id}>{g.name} <Button disabled={busy} onClick={()=>run(async()=>{await call(`/${kind}/${id}/grants`,'DELETE',{email:g.email});setGrants(gs=>gs.filter(x=>x.user_id!==g.user_id));})}>Revogar</Button></p>)}</section>}
  </ReportsDrawer></>;
}
