import React,{useState} from 'react';
import {ReportsActionButton as Button} from './ReportsActionButton.jsx';
import {ReportsFieldInput} from './ReportsFieldInput.jsx';
import {ReportsRelationships} from './ReportsRelationships.jsx';
export function ReportsCustomers({data,save,busy}) {
 const [name,setName]=useState(''),[editing,setEditing]=useState(null),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();try{await save(editing?`/customers/${editing.id}`:'/customers',{name},true,editing?'PATCH':'POST');setName('');setEditing(null);setError('');}catch(e){setError(e.message);}};
 return <section className="reports-panel"><p className="reports-panel-note">Organize sua operação. Marcas e projetos são opcionais.</p>{error&&<p role="alert">{error}</p>}{data.client.role==='admin'&&<form className="reports-form" onSubmit={submit}><label>Nome do cliente ou anunciante<ReportsFieldInput required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><div><Button type="submit" disabled={busy}>{editing?'Salvar nome':'Adicionar cliente'}</Button>{editing&&<Button onClick={()=>{setEditing(null);setName('');}}>Cancelar</Button>}</div></form>}<div className="reports-table-wrap"><table><thead><tr><th>Cliente / anunciante</th><th>Contas</th><th>Campanhas</th><th>Ações</th></tr></thead><tbody>{(data.customers||[]).map(c=><tr key={c.id}><td>{c.name}</td><td>{data.accounts.filter(a=>a.customer_id===c.id).length}</td><td>{data.campaigns.filter(a=>a.customer_id===c.id).length}</td><td>{data.client.role==='admin'&&<Button onClick={()=>{setEditing(c);setName(c.name);}}>Editar</Button>}<ReportsRelationships data={data} kind="customer" id={c.id} name={c.name}/></td></tr>)}</tbody></table>{!data.customers?.length&&<p>Sem clientes cadastrados. Você também pode operar recursos da própria empresa.</p>}</div></section>;
}
