-- Ten read-only daily workflows. Runtime tool permissions remain code allowlisted.
INSERT INTO cadu_chat_plugins (id, kind, name, category, sort_order, selectable) VALUES
 ('market-radar', 'plugin', 'Radar de mercado', 'Pesquisa', 100, TRUE),
 ('audience-map', 'plugin', 'Mapa de audiência', 'Planejamento', 110, TRUE),
 ('investment-simulator', 'plugin', 'Simulador de investimento', 'Planejamento', 120, TRUE),
 ('media-plan-audit', 'plugin', 'Auditoria do plano', 'Planejamento', 130, TRUE),
 ('campaign-tracker', 'plugin', 'Acompanhamento de campanha', 'Análise', 140, TRUE),
 ('creative-concept', 'plugin', 'Conceito criativo', 'Criação', 150, TRUE),
 ('channel-copy', 'plugin', 'Copy por canal', 'Criação', 160, TRUE),
 ('page-review', 'plugin', 'Revisor de página', 'Criação', 170, TRUE),
 ('meeting-copilot', 'plugin', 'Copiloto de reunião', 'Atendimento', 180, TRUE),
 ('client-delivery', 'plugin', 'Atendimento e entregas', 'Atendimento', 190, TRUE)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, sort_order=EXCLUDED.sort_order, selectable=TRUE, enabled=TRUE, updated_at=NOW();
UPDATE cadu_chat_plugin_versions SET is_current=FALSE WHERE plugin_id IN ('market-radar', 'audience-map', 'investment-simulator', 'media-plan-audit', 'campaign-tracker', 'creative-concept', 'channel-copy', 'page-review', 'meeting-copilot', 'client-delivery') AND version <> '1.0.0' AND is_current;
INSERT INTO cadu_chat_plugin_versions (plugin_id, version, maturity, description, manifest, changelog, is_current) VALUES
 ('market-radar', '1.0.0', 'active', 'Notícias e movimentos de concorrentes com fontes.', '{"triggers": ["/market-radar"], "internal_tools": ["web.search"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('audience-map', '1.0.0', 'active', 'Hipóteses de público, canais e sinais de pesquisa.', '{"triggers": ["/audience-map"], "internal_tools": ["web.search", "planner.research_plan_inputs"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('investment-simulator', '1.0.0', 'active', 'Cenários de verba e premissas para mídia.', '{"triggers": ["/investment-simulator"], "internal_tools": ["planner.research_plan_inputs"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('media-plan-audit', '1.0.0', 'active', 'Revê coerência, riscos e lacunas do plano.', '{"triggers": ["/media-plan-audit"], "internal_tools": ["planner.get_media_plan", "planner.research_plan_inputs"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('campaign-tracker', '1.0.0', 'active', 'Lê relatórios revisados e sugere próximos passos.', '{"triggers": ["/campaign-tracker"], "internal_tools": ["reports.get_recent_project_metrics"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('creative-concept', '1.0.0', 'active', 'Direção, mensagem e variações para campanha.', '{"triggers": ["/creative-concept"], "internal_tools": [], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('channel-copy', '1.0.0', 'active', 'Textos prontos para formatos e canais escolhidos.', '{"triggers": ["/channel-copy"], "internal_tools": [], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('page-review', '1.0.0', 'active', 'Avalia clareza, oferta, CTA e fricções.', '{"triggers": ["/page-review"], "internal_tools": ["web.read"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('meeting-copilot', '1.0.0', 'active', 'Pauta, resumo e encaminhamentos objetivos.', '{"triggers": ["/meeting-copilot"], "internal_tools": ["google.list_meet_artifacts"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE),
 ('client-delivery', '1.0.0', 'active', 'Organiza status, pendências e mensagem ao cliente.', '{"triggers": ["/client-delivery"], "internal_tools": ["projects.list_tasks", "projects.list_resources"], "context": ["conversation", "project or brand when selected"], "external_connectors": [], "inputs": ["objective"], "outputs": ["answer in chat"], "known_gaps": []}'::jsonb, 'Fluxo de leitura e resposta no chat.', TRUE)
ON CONFLICT (plugin_id, version) DO UPDATE SET maturity=EXCLUDED.maturity, description=EXCLUDED.description, manifest=EXCLUDED.manifest, is_current=TRUE;
