-- Reports-owned client spaces. They are intentionally independent from tbl_cliente.
CREATE TABLE IF NOT EXISTS cadu_reports_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000) PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES tbl_cliente(id_cliente),
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','archived')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by BIGINT NOT NULL REFERENCES tbl_contato_cliente(id_contato_cliente),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT cadu_reports_clients_org_slug_unique UNIQUE (organization_id,slug),
    CONSTRAINT cadu_reports_clients_id_org_unique UNIQUE (id,organization_id)
);
CREATE INDEX IF NOT EXISTS cadu_reports_clients_org_status_idx
    ON cadu_reports_clients (organization_id,status,name);

-- cadu_reports_user_access accepts either legacy CRM client IDs or native
-- Reports client IDs. Authorization is enforced by reports_access.resolve().
DO $$
DECLARE constraint_name TEXT;
BEGIN
    FOR constraint_name IN
        SELECT conname FROM pg_constraint
         WHERE conrelid='public.cadu_reports_user_access'::regclass
           AND contype='f'
           AND pg_get_constraintdef(oid) LIKE 'FOREIGN KEY (client_id) REFERENCES tbl_cliente%'
    LOOP
        EXECUTE format('ALTER TABLE public.cadu_reports_user_access DROP CONSTRAINT %I', constraint_name);
    END LOOP;
END $$;

ALTER TABLE cadu_reports_user_access
    ALTER COLUMN client_id TYPE BIGINT USING client_id::BIGINT;

-- Campaigns may be linked to a project later; an empty reference is valid.
ALTER TABLE cadu_reports_campaigns
    ADD COLUMN IF NOT EXISTS project_ref VARCHAR(160);
CREATE INDEX IF NOT EXISTS cadu_reports_campaigns_project_idx
    ON cadu_reports_campaigns (organization_id,client_id,project_ref)
    WHERE project_ref IS NOT NULL;
