-- Versioned catalog update; preserve later versions and administrative enablement.
INSERT INTO cadu_chat_plugin_versions (plugin_id, version, maturity, description, manifest, changelog, is_current) VALUES
 ('market-radar', '1.1.0', 'active', 'Notícias e movimentos de concorrentes com fontes.', '{"triggers": ["/market-radar"], "internal_tools": ["web.search"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Pesquisa sob demanda; não há monitoramento automático."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('audience-map', '1.1.0', 'active', 'Hipóteses de público, canais e sinais de pesquisa.', '{"triggers": ["/audience-map"], "internal_tools": ["web.search", "planner.research_plan_inputs"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Segmentos são hipóteses quando não existe dado de audiência verificável."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('investment-simulator', '1.1.0', 'active', 'Cenários de verba e premissas para mídia.', '{"triggers": ["/investment-simulator"], "internal_tools": ["planner.research_plan_inputs"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Cenários não são cotações nem previsões de resultado."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('media-plan-audit', '1.1.0', 'active', 'Revê coerência, riscos e lacunas do plano.', '{"triggers": ["/media-plan-audit"], "internal_tools": ["planner.list_plans", "planner.get_media_plan"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["A listagem de planos não contém o plano completo; é preciso selecionar ou fornecer um plano."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('campaign-tracker', '1.1.0', 'active', 'Lê relatórios revisados e sugere próximos passos.', '{"triggers": ["/campaign-tracker"], "internal_tools": ["reports.get_recent_project_metrics"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Usa até três relatórios revisados do projeto; não há métricas em tempo real."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('creative-concept', '1.1.0', 'active', 'Direção, mensagem e variações para campanha.', '{"triggers": ["/creative-concept"], "internal_tools": [], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Conceitos são propostas e requerem revisão da marca."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('channel-copy', '1.1.0', 'active', 'Textos prontos para formatos e canais escolhidos.', '{"triggers": ["/channel-copy"], "internal_tools": [], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Limites de formato dependem do canal informado e devem ser verificados antes da publicação."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('page-review', '1.1.0', 'active', 'Avalia clareza, oferta, CTA e fricções.', '{"triggers": ["/page-review"], "internal_tools": ["web.read"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["A análise depende do conteúdo público acessível ou do texto fornecido."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('meeting-copilot', '1.1.0', 'active', 'Pauta, resumo e encaminhamentos objetivos.', '{"triggers": ["/meeting-copilot"], "internal_tools": ["google.list_meet_artifacts"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["A listagem do Meet contém metadados, não transcrições."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE),
 ('client-delivery', '1.1.0', 'active', 'Organiza status, pendências e mensagem ao cliente.', '{"triggers": ["/client-delivery"], "internal_tools": ["projects.list_tasks", "projects.list_resources"], "context": ["conversation", "selected project or brand when available"], "external_connectors": [], "known_gaps": ["Prepara mensagem; não envia nem altera tarefas automaticamente."], "inputs": ["objective and available context"], "outputs": ["answer or draft in chat"]}'::jsonb, 'Escopo e limites refinados.', FALSE)
ON CONFLICT (plugin_id, version) DO NOTHING;
UPDATE cadu_chat_plugin_versions old SET is_current=FALSE WHERE old.plugin_id IN ('market-radar', 'audience-map', 'investment-simulator', 'media-plan-audit', 'campaign-tracker', 'creative-concept', 'channel-copy', 'page-review', 'meeting-copilot', 'client-delivery') AND old.version='1.0.0' AND old.is_current AND NOT EXISTS (SELECT 1 FROM cadu_chat_plugin_versions newer WHERE newer.plugin_id=old.plugin_id AND newer.is_current AND newer.version > '1.1.0');
UPDATE cadu_chat_plugin_versions current SET is_current=TRUE WHERE current.plugin_id IN ('market-radar', 'audience-map', 'investment-simulator', 'media-plan-audit', 'campaign-tracker', 'creative-concept', 'channel-copy', 'page-review', 'meeting-copilot', 'client-delivery') AND current.version='1.1.0' AND NOT current.is_current AND NOT EXISTS (SELECT 1 FROM cadu_chat_plugin_versions newer WHERE newer.plugin_id=current.plugin_id AND newer.is_current AND newer.version > '1.1.0');
