-- Perfil da audiência e melhor uso dos canais, de pesquisa pública de 2026-10-06 (só Brasil, texto revisado, sem números sem fonte).
-- Idempotente e respeitosa com edição humana: só preenche campo vazio. Depende de add_cadu_canais_fontes_metricas.sql.
UPDATE cadu_canais c SET
    perfil_audiencia = COALESCE(NULLIF(BTRIM(c.perfil_audiencia), ''), v.perfil),
    melhor_uso = COALESCE(NULLIF(BTRIM(c.melhor_uso), ''), v.uso),
    fontes_metricas = COALESCE(c.fontes_metricas, '{}'::jsonb) || jsonb_build_object('perfil',
        jsonb_build_object('fontes', v.fontes, 'pesquisado_em', '2026-10-06')),
    metricas_atualizadas_em = COALESCE(c.metricas_atualizadas_em, NOW())
FROM (VALUES
  ($q$experian-dmp$q$, $q$A base pública indicada pela Serasa/Serasa Experian para ativação publicitária é majoritariamente adulta, com segmentações disponíveis de 18–65+ anos, por gênero, classe social (A–E), escolaridade e ocupação/profissão.$q$, $q$Melhor para campanhas de performance e segmentação baseada em dados financeiros, crédito e comportamento de consumo, especialmente para públicos adultos com intenção de compra ou risco/propensão financeira.$q$, $q$["https://www.serasaexperian.com.br/conteudos/marketing/tudo-o-que-voce-precisa-saber-sobre-dmp/", "https://www.serasaexperian.com.br/solucoes/ativacoes-digitais/", "https://www.serasaexperian.com.br/solucoes/analise-de-mercado-e-segmentacao-de-campanhas/", "https://www.serasa.com.br/seja-parceiro/"]$q$::jsonb),
  ($q$eletromidia$q$, $q$A Eletromidia se posiciona com alcance amplo em OOH/DOOH no Brasil, cobrindo seis verticais e 11 maiores mercados, com destaque para uma audiência urbana de alto fluxo. A própria empresa cita que 89% da população brasileira foi impactada por OOH nos últimos 30 dias.$q$, $q$Mais indicado para cobertura de massa com reforço de frequência e impacto contextual em jornadas urbanas, especialmente em grandes capitais e ativos premium.$q$, $q$["https://www.eletromidia.com.br/", "https://anuncie.eletromidia.com.br/", "https://www.eletromidia.com.br/imprensa", "https://janela.com.br/2026/05/27/eletromidia-apresenta-seu-projeto-de-ooh-copa-2026-para-o-mercado-publicitario/"]$q$::jsonb),
  ($q$99$q$, $q$A 99 no Brasil é uma plataforma massiva de mobilidade com presença em 3.300 cidades, mais de 1 milhão de motoristas parceiros ativos e base amplamente urbana. Os materiais públicos citam foco em consumidores em movimento e uso forte em praças como São Paulo, Belo Horizonte e Porto Alegre. As campanhas recentes reforçam apelo a adultos urbanos de diferentes classes, com uso em contextos de deslocamento e alta recorrência.$q$, $q$Boa para campanhas de alcance e contexto de mobilidade, com mensagem orientada a geolocalização e presença ao longo da jornada urbana.$q$, $q$["https://99app.com/99ads/", "https://propmark.com.br/anunciantes/99-transforma-dados-de-mobilidade-em-nova-frente-de-midia-por-meio-da-99ads/"]$q$::jsonb),
  ($q$ifood$q$, $q$O canal iFood Ads no Brasil declara base de 55 milhões de usuários cadastrados, com operação que cobre grandes centros e cidades do interior.$q$, $q$Bom para campanhas de conversão e consideração no ecossistema de delivery, aproveitando audiência de alta intenção e presença omnichannel.$q$, $q$["https://institucional.ifood.com.br/impacto-social/alianca-pela-mobilidade-sustentavel/", "https://institucional.ifood.com.br/novos-negocios/ifood-ads/", "https://www.uber.com/br/pt-br/newsroom/uber-e-ifood-anunciam-parceria-no-brasil/"]$q$::jsonb),
  ($q$logan$q$, $q$Audiência mobile ampla no Brasil, com foco em usuários de dispositivos móveis e comportamentos cross-device. A Logan se posiciona para atingir pessoas em mobilidade, com menções públicas a cobertura em classes ABC e a base de mais de 300 milhões de usuários na América Latina em sua comunicação institucional.$q$, $q$Melhor para campanhas mobile-first e cross-device que buscam segmentação por comportamento, geolocalização e formatos interativos de alto engajamento.$q$, $q$["https://logan.ai/", "https://logan.ai/logan-ads/", "https://logan.ai/loganads/industria.html", "https://propmark.com.br/logan-adota-zero-party-data-para-capturar-dados-sem-intermediarios/"]$q$::jsonb),
  ($q$uber$q$, $q$A Uber no Brasil alcança usuários de alta intenção no momento de deslocamento, com forte relevância para adultos urbanos e digitalmente ativos. A própria Uber descreve a audiência como pessoas em “momentos de alta intenção” ao longo da jornada.$q$, $q$Melhor para campanhas de alta intenção, ativação de marca e oferta com incentivo, especialmente quando a marca quer influenciar a decisão durante o deslocamento.$q$, $q$["https://www.uber.com/br/pt-br/advertising/", "https://www.uber.com/br/pt-br/newsroom/advertising/", "https://www.uber.com/br/en/advertising/ads-go/", "https://www.uber.com/br/pt-br/blog/mobility-offers-premium-eats-formats-offsite/"]$q$::jsonb),
  ($q$amazon-ads$q$, $q$No Brasil, a Amazon Ads atende anunciantes de todos os portes e segmentos, em todos os 26 estados e no DF, com orçamentos flexíveis e sem exigir que a marca venda na loja Amazon. Em termos públicos citados pela própria Amazon, há foco relevante em PMEs brasileiras e em públicos qualificados para vídeo/streaming.$q$, $q$Mais indicado para construção de consideração e conversão no ecossistema Amazon, combinando intenção de busca no marketplace com alcance programático em ambientes premium dentro e fora da Amazon.$q$, $q$["https://www.aboutamazon.com.br/noticias/ads/amazon-ads-construida-para-conectar-marcas-a-vida-real-dos-consumidores", "https://www.aboutamazon.com.br/noticias/ads/ia-abre-as-portas-da-publicidade-premium-para-pmes-brasileiras", "https://advertising.amazon.com/pt-br/solutions/products/amazon-dsp", "https://www.aboutamazon.com.br/noticias/ads/o-que-a-amazon-planeja-para-o-ads-agent-no-brasil"]$q$::jsonb),
  ($q$google-dv360$q$, NULL, $q$Mais indicado para planejar, comprar, medir e otimizar mídia programática multicanal em uma única plataforma.$q$, $q$["https://marketingplatform.google.com/intl/pt_BR/about/display-video-360/", "https://developers.google.com/display-video/api/guides/quickstart/overview?hl=pt-br", "https://developers.google.com/display-video/api/structured-data-file/v9-1/Campaign?hl=pt-br", "https://cloud.google.com/looker/docs/studio/connect-to-display--video-360?hl=pt-BR"]$q$::jsonb),
  ($q$instagram$q$, $q$Em 2025, a audiência adulta de Instagram no Brasil é majoritariamente feminina: 57,8% mulheres e 42,2% homens. Estimativas públicas de ferramentas de anúncio indicam alcance de cerca de 147 milhões de usuários no país no fim de 2025. Em recortes públicos de planejadores de mídia, a base é forte em 18-34 anos e concentrada em áreas urbanas, com uso amplo entre classes consumidoras digitais.$q$, $q$Canal forte para alcance, consideração e conversão mobile-first, especialmente com criativos verticais e remarketing.$q$, $q$["https://datareportal.com/reports/digital-2025-brazil", "https://datareportal.com/reports/digital-2026-brazil", "https://affectgroup.com/blog/meta-ads-audience-in-brazil-facebook-and-instagram-capacity-in-2025/"]$q$::jsonb),
  ($q$kwai$q$, NULL, $q$Mais forte para awareness e performance em funil completo, especialmente para campanhas com vídeo vertical, social commerce e ativações criativas de alto engajamento.$q$, $q$["https://www.kwai.com/business/pt-BR", "https://www.kwai.com/newsroom", "https://www.prnewswire.com/news-releases/ias-announces-exclusive-first-to-market-partnership-with-kwai-for-business-to-provide-content-level-brand-safety-and-suitability-measurement-for-advertisers-302335829.html", "https://fastcompanybrasil.com/fastco-works/kwai-summit-ads/"]$q$::jsonb),
  ($q$linkedin$q$, $q$LinkedIn no Brasil é predominantemente usado por profissionais em idade ativa, com forte presença de decisores e influenciadores B2B. A segmentação pública disponível aponta foco em dados profissionais como cargo, senioridade, setor e tamanho de empresa, mais do que em idade/gênero.$q$, $q$Melhor para mídia B2B e geração de demanda qualificada, especialmente quando a audiência pode ser definida por cargo, empresa e senioridade.$q$, $q$["https://business.linkedin.com/br/pt/advertise/ads/campaign-manager", "https://business.linkedin.com/br/pt/advertise/ads/best-practices/create-your-first-campaign", "https://www.linkedin.com/help/lms/answer/a424660/opcoes-de-segmentacao-para-linkedin-ads?lang=pt", "https://www.linkedin.com/help/lms/answer/a425060?lang=pt-BR"]$q$::jsonb),
  ($q$tiktok$q$, $q$Usuários do TikTok no Brasil concentram-se sobretudo em públicos mais jovens e mobile-first.$q$, $q$Canal indicado para alcance incremental, descoberta e performance em vídeo curto, especialmente em mobile-first e e-commerce.$q$, $q$["https://ads.tiktok.com/business/pt-BR", "https://newsroom.tiktok.com/tiktok-world-2026-mostra-evoluo-do-tiktok-como-plataforma-de-performance?lang=pt-BR", "https://ads.tiktok.com/resources/help/article/tiktok-ads-policy-ad-format-and-functionality?lang=en"]$q$::jsonb),
  ($q$twitch$q$, $q$A Twitch no Brasil é fortemente concentrada em público jovem-adulto, com destaque para faixas de 18–34 anos e interesse em jogos, cultura pop e conteúdo ao vivo. A plataforma é usada tanto por espectadores quanto por criadores, com consumo em desktop e mobile.$q$, $q$Ideal para awareness e consideração em públicos jovens e engajados, especialmente em contextos de gaming, entretenimento e cultura digital ao vivo.$q$, $q$["https://advertising.amazon.com/pt-br/channels/twitch", "https://advertising.amazon.com/resources/ad-specs/twitch", "https://help.twitch.tv/s/article/ads-manager?language=pt_BR"]$q$::jsonb),
  ($q$youtube$q$, $q$O YouTube no Brasil alcança uma audiência ampla, com forte uso em mobile e consumo de vídeo para entretenimento, aprendizado e descoberta de conteúdo.$q$, $q$Bom para alcance massivo com vídeo e para considerar jornadas de topo e meio de funil, especialmente quando combinados com segmentação por interesses, remarketing e públicos personalizados.$q$, $q$["https://business.google.com/br/ad-solutions/youtube-ads/", "https://support.google.com/google-ads/answer/9427120?hl=pt-BR", "https://developers.google.com/google-ads/api/docs/release-notes?hl=pt-br"]$q$::jsonb),
  ($q$amazon-music$q$, NULL, $q$Boa opção para awareness e consideração em momentos de escuta contínua, com alcance em ambientes sem tela e reforço visual via companion banner.$q$, $q$["https://advertising.amazon.com/pt-br/solutions/products/audio-ads?ref_=a20m_us_fnav_p_aa", "https://advertising.amazon.com/pt-br/resources/faq", "https://advertising.amazon.com/resources/ad-specs/audio-ads", "https://advertising.amazon.com/pt-br/resources/ad-specs"]$q$::jsonb),
  ($q$deezer$q$, NULL, $q$Boa para alcance incremental em audiência engajada com música e áudio, especialmente em campanhas de awareness e consideração com segmentação contextual e demográfica.$q$, $q$["https://newsroom-deezer.com/2025/07/deezer-azerion-deal-in-brazil/", "https://newsroom-deezer.com/br/2026/03/deezer-for-business-deezer-anuncia-plataforma-de-parcerias-reformulada-para-acelerar-nova-fase-de-crescimento/", "https://support.deezer.com/hc/en-gb/articles/36339056473629-Distribute-Deezer-in-Latin-America-if-you-are-an-ISP"]$q$::jsonb),
  ($q$disney-plus$q$, $q$Público amplo de streaming no Brasil, com forte presença de entretenimento familiar e esportes.$q$, $q$Bom para awareness e consideração em streaming premium, especialmente em entretenimento, família e esportes, com forte apelo para marcas que buscam contexto seguro e segmentação por audiência.$q$, $q$["https://imprensa.disney.com.br/novidades/magia-comercial-as-campanhas-e-ativacoes-de-2024-inspiradas-em-historias-e-personagens-disney", "https://mercadoeconsumo.com.br/02/07/2024/retail-media/mercado-ads-anuncia-alianca-com-disney-para-retail-media-com-70-da-sua-capacidade-vendida/", "https://telaviva.com.br/17/12/2025/disney-e-amazon-ads-anunciam-colaboracao-programatica-no-brasil/", "https://www.disneyplus.com/en-br"]$q$::jsonb),
  ($q$globoplay$q$, $q$A audiência publicitária do Globoplay é formada por usuários com dados de perfil ligados ao Globo ID, incluindo idade, gênero, interesses e até renda/poder de compra em ativações ao vivo.$q$, $q$Bom para alcance premium com segmentação por dados próprios da Globo, especialmente em campanhas com vídeo, cobertura regional e ativações em conteúdo ao vivo.$q$, $q$["https://globoads.globo.com/para-o-seu-negocio/anunciar-no-globoplay", "https://globoads.globo.com/para-o-seu-negocio/anunciar-no-globoplay/intervalo-globoplay", "https://globoads.globo.com/upfront/2026/globoplay", "https://ajuda.globoads.globo.com/s/article/Perguntas-frequentes-sobre-an%C3%BAncios-digitais"]$q$::jsonb),
  ($q$hbo-max$q$, $q$Público amplo e premium, com plano com anúncios voltado a consumidores que aceitam publicidade em troca de preço mais acessível.$q$, $q$Boa opção para campanhas de alcance e brand safety em ambiente premium de streaming, especialmente em lançamentos, franquias fortes e eventos ao vivo.$q$, $q$["https://www.wbdforbrands.com.br/landing/oportunidades-hbo-max/", "https://www.adnews.com.br/max-chega-ao-brasil-com-novas-oportunidades-comerciais", "https://www.thedailytelevision.com/articulo/publicidad/max-abre-nuevas-oportunidades-comerciales-para-anunciantes-en-latam"]$q$::jsonb),
  ($q$netflix$q$, $q$No Brasil, o plano com anúncios da Netflix atingia 29,2 milhões de pessoas ativas por mês em 2023, com evolução recente da base de assinantes com ads.$q$, $q$Melhor para awareness e consideração com alta atenção em streaming premium, especialmente para campanhas que querem combinar segmentação avançada e mensuração cross-media.$q$, $q$["https://about.netflix.com/pt_br/news/netflix-third-season-of-ads-and-a-look-ahead-at-whats-next-brazil", "https://about.netflix.com/pt_br/news/netflix-and-embratur-announce-cooperation-agreement", "https://about.netflix.com/pt_br/news/one-year-into-netflix-ads", "https://telaviva.com.br/12/11/2024/netflix-lancara-tecnologia-de-publicidade-interna-em-2025"]$q$::jsonb),
  ($q$paramount-plus$q$, $q$Público amplo de streaming premium no Brasil.$q$, $q$Mais indicado para awareness e consideração de marca em ambiente premium de streaming, com reforço em esportes e entretenimento.$q$, $q$["https://www.centralcomm.media/canal/paramount-plus", "https://paramountforbusiness.com.br/", "https://legal.paramount.com/br/pt/pplus/termsofuse", "https://www.meioemensagem.com.br/midia/stremings-publicidade"]$q$::jsonb),
  ($q$podcast-ads$q$, $q$No Brasil, a segmentação pública da Spotify Ads para podcasts indica alcance por idade, gênero e localização. O material em português também menciona entrega em desktop, mobile, web player, TV, carro e smart speaker, sugerindo uso amplo e digital-first.$q$, $q$Boa opção para awareness e consideração com segmentação básica e mensuração de alcance, frequência e conclusão em ambientes de áudio premium.$q$, $q$["https://help.adanalytics.spotify.com/about-ad-analytics", "https://ads.spotify.com/pt-BR/experiencias-publicitarias/podcast-ads-specs/", "https://ads.spotify.com/pt-BR/noticias-insights/guia-para-comecar-seus-anuncios-em-podcasts/", "https://newsroom.spotify.com/2025-04-02/the-three-key-takeaways-for-advertisers-from-our-spotify-advance-event/"]$q$::jsonb),
  ($q$prime-video$q$, $q$Prime Video no Brasil passou a ter anúncios limitados a partir de 2025, com opção sem anúncios para quem desejar. O serviço se posiciona como alcance amplo em streaming premium, com foco em membros Prime e audiência de entretenimento/esportes ao vivo.$q$, $q$Indicado para awareness e consideração em ambiente de streaming premium, especialmente em campanhas que queiram combinar vídeo, entretenimento e sinais first-party da Amazon.$q$, $q$["https://advertising.amazon.com/products/prime-video-ads", "https://advertising.amazon.com/library/news/unboxed-prime-video-advertising", "https://www.aboutamazon.com.br/noticias/entretenimento/uma-atualizacao-sobre-o-prime-video", "https://www.aboutamazon.com.br/noticias/entretenimento/agora-voce-pode-interagir-com-marcas-enquanto-assiste-streaming-sem-perder-nenhuma-cena"]$q$::jsonb),
  ($q$samsung-tv-plus$q$, $q$Públicos mencionados publicamente pela Samsung incluem famílias da geração millennial e espectadores influentes. A própria Samsung Ads também cita audiência premium com 68% classe A/B em materiais comerciais do Brasil.$q$, $q$Boa opção para branding, alcance incremental e segmentação em CTV/streaming com ambiente premium e inventário de TV conectada.$q$, $q$["https://news.samsung.com/br/samsung-ads-chega-ao-brasil-como-nova-opcao-de-midia-nas-tvs-samsung", "https://news.samsung.com/br/samsung-tv-plus-inicia-2026-com-mais-de-100-milhoes-de-usuarios-ativos-mensais", "https://www.centralcomm.media/canal/samsung-tv-plus"]$q$::jsonb),
  ($q$spotify$q$, $q$Spotify é uma plataforma massiva de streaming no Brasil, com alcance em usuários de música e podcasts, especialmente em audiências mobile e em momentos de atenção ativa.$q$, $q$Melhor para alcance em áudio com alta atenção, reforço de marca e ativações combinando áudio, vídeo e display.$q$, $q$["https://ads.spotify.com/pt-BR/ad-formats/", "https://ads.spotify.com/pt-BR/experiencias-publicitarias/", "https://ads.spotify.com/pt-BR/ad-measurement/", "https://adshelp.spotify.com/HelpCenter/s/article/Campanhas-anuncios-e-grupos-de-anuncios-BR?language=pt_BR"]$q$::jsonb)
) AS v(slug, perfil, uso, fontes)
WHERE c.slug = v.slug;
