"""Curated commercial profile (one-sentence pitch, no audience numbers, and the main sections) of the portals after the Top 10.

The catalog text of these portals is generic ("Portal nacional de ..."); this is the editorial summary a media planner reads first.
"""
PROFILES = {
    'autoesporte.globo.com': ('Revista de carros da Globo, com testes, lançamentos, comparativos e guias de compra.', ['Notícias', 'Testes', 'Lançamentos', 'Carros elétricos', 'Motos', 'Guia de compra', 'Vídeos']),
    'casaejardim.globo.com': ('Revista de decoração, arquitetura, jardinagem e vida em casa, com projetos e dicas práticas.', ['Decoração', 'Arquitetura', 'Jardinagem', 'Reforma', 'Cozinha', 'Pets', 'Receitas']),
    'revistacrescer.globo.com': ('Revista para pais e mães, com conteúdo sobre gravidez, bebês, saúde e educação das crianças.', ['Gravidez', 'Bebês', 'Crianças', 'Saúde', 'Educação', 'Comportamento', 'Nomes']),
    'globo.com': ('Portal do maior grupo de mídia do país, que reúne notícias, esportes, TV e entretenimento das marcas Globo.', ['Notícias', 'Esportes', 'Entretenimento', 'Vídeos', 'Economia', 'Tecnologia']),
    'gshow.globo.com': ('Portal de entretenimento da Globo, com novelas, programas, reality shows, famosos e bastidores da TV.', ['Novelas', 'Reality shows', 'Programas', 'Famosos', 'Séries', 'Música']),
    'marieclaire.globo.com': ('Revista feminina de moda, beleza, comportamento e cultura.', ['Moda', 'Beleza', 'Comportamento', 'Cultura', 'Bem-estar', 'Casa']),
    'quem.globo.com': ('Revista de celebridades e vida dos famosos, com coberturas de eventos, TV e comportamento.', ['Celebridades', 'TV', 'Moda', 'Beleza', 'Comportamento', 'Casamentos']),
    'valor.globo.com': ('Jornal de economia e negócios, referência em mercado financeiro, empresas, política econômica e carreira.', ['Finanças', 'Empresas', 'Brasil', 'Mundo', 'Agronegócios', 'Legislação', 'Carreira']),
    'vogue.globo.com': ('Revista de moda e estilo de vida, com desfiles, beleza, cultura e lifestyle de luxo.', ['Moda', 'Beleza', 'Lifestyle', 'Cultura', 'Celebridades', 'Casa']),
    'band.uol.com.br': ('Portal da Band, com notícias, esportes, entretenimento e a programação da emissora.', ['Notícias', 'Esportes', 'Entretenimento', 'Programas', 'Vídeos', 'Economia']),
    'bol.uol.com.br': ('Portal de entretenimento e serviços do UOL, com e-mail, notícias, horóscopo e variedades.', ['Notícias', 'Entretenimento', 'Esportes', 'Horóscopo', 'Tecnologia', 'Vida e estilo']),
    'brasilescola.uol.com.br': ('Portal de estudos para estudantes do ensino fundamental e médio, com conteúdo escolar e de vestibular.', ['Matérias escolares', 'Redação', 'Vestibular', 'Enem', 'Concursos', 'Cursos']),
    'drauziovarella.uol.com.br': ('Portal de saúde do médico Drauzio Varella, com informação sobre doenças, bem-estar e prevenção.', ['Doenças', 'Saúde', 'Bem-estar', 'Alimentação', 'Mulher', 'Prevenção']),
    'hugogloss.uol.com.br': ('Portal de celebridades e cultura pop, com famosos, TV, música e fofocas.', ['Celebridades', 'TV', 'Música', 'Cinema', 'Reality shows', 'Moda']),
    'mundoeducacao.uol.com.br': ('Portal educacional com conteúdo escolar, redação e preparação para provas.', ['Matérias escolares', 'Redação', 'Enem', 'Vestibular', 'Concursos', 'Cursos']),
    'rollingstone.uol.com.br': ('Revista de música e cultura, com rock, pop, cinema, séries e entrevistas.', ['Música', 'Cinema', 'Séries', 'Cultura pop', 'Entrevistas', 'Shows']),
    'letras.mus.br': ('Grande acervo de letras e vídeos de música, com artistas, ranking e traduções.', ['Letras', 'Artistas', 'Ranking', 'Tradução', 'Estilos musicais', 'Vídeos']),
    'br.investing.com': ('Portal de mercado financeiro, com cotações, notícias, análises e ferramentas para investidores.', ['Mercados', 'Ações', 'Moedas', 'Criptomoedas', 'Commodities', 'Análises']),
    'claudia.abril.com.br': ('Revista feminina com comportamento, carreira, bem-estar, moda e família.', ['Comportamento', 'Carreira', 'Bem-estar', 'Moda', 'Família', 'Receitas']),
    'quatrorodas.abril.com.br': ('Revista de carros e motores, com testes, lançamentos, comparativos e dicas de manutenção.', ['Notícias', 'Testes', 'Lançamentos', 'Elétricos', 'Usados', 'Dicas']),
    'super.abril.com.br': ('Revista de ciência, tecnologia, comportamento e curiosidades.', ['Ciência', 'Tecnologia', 'Comportamento', 'Saúde', 'História', 'Mundo']),
    'veja.abril.com.br': ('Revista semanal de notícias, com reportagens de política, economia, comportamento e opinião.', ['Brasil', 'Mundo', 'Economia', 'Política', 'Saúde', 'Cultura', 'Colunas']),
    'viagemeturismo.abril.com.br': ('Revista de viagem e turismo, com destinos, roteiros, dicas e guias no Brasil e no mundo.', ['Destinos', 'Roteiros', 'Dicas', 'Hotéis', 'Gastronomia', 'Guias']),
    'cifraclub.com.br': ('Portal de cifras e partituras para violão, guitarra, teclado e outros instrumentos.', ['Cifras', 'Artistas', 'Aulas', 'Afinador', 'Partituras', 'Vídeos']),
    'tuasaude.com': ('Portal de saúde e bem-estar, com informação sobre sintomas, alimentação, exercícios e remédios.', ['Doenças', 'Alimentação', 'Exercícios', 'Remédios', 'Gravidez', 'Bem-estar']),
    'olhardigital.com.br': ('Portal de tecnologia, com notícias, análises, ciência, games e novidades do mundo digital.', ['Notícias', 'Ciência', 'Games', 'Segurança', 'Mobilidade', 'Vídeos']),
    'espn.com.br': ('Portal esportivo com futebol, NBA, tênis, automobilismo e outros esportes, e conteúdo de TV.', ['Futebol', 'NBA', 'Tênis', 'Automobilismo', 'NFL', 'Vídeos']),
    'ig.com.br': ('Portal de notícias, entretenimento e serviços, com e-mail, esportes, economia e variedades.', ['Notícias', 'Esportes', 'Economia', 'Entretenimento', 'Gente', 'Tecnologia']),
    'lance.com.br': ('Jornal esportivo dedicado ao futebol, com cobertura diária de clubes, campeonatos e mercado da bola.', ['Futebol', 'Brasileirão', 'Mercado da bola', 'Seleção', 'Futebol internacional', 'Outros esportes']),
    'climatempo.com.br': ('Portal de previsão do tempo, com clima por cidade, alertas, imagens de satélite e notícias.', ['Previsão por cidade', 'Alertas', 'Satélite', 'Notícias', 'Clima agro', 'Praias']),
    'ndmais.com.br': ('Portal de notícias de Santa Catarina, com cobertura regional, política, cidades e esportes.', ['Santa Catarina', 'Política', 'Cidades', 'Esportes', 'Economia', 'Entretenimento']),
    'correio24horas.com.br': ('Jornal da Bahia, com cobertura de Salvador e do interior, política, cidades e esportes.', ['Bahia', 'Salvador', 'Política', 'Esportes', 'Economia', 'Entretenimento']),
    'tudocelular.com': ('Portal de smartphones e tecnologia móvel, com notícias, análises, comparativos e ofertas.', ['Notícias', 'Análises', 'Comparativos', 'Lançamentos', 'Dicas', 'Ofertas']),
    'nsctotal.com.br': ('Portal de notícias de Santa Catarina, do grupo NSC, com cobertura regional e esportiva.', ['Santa Catarina', 'Política', 'Esportes', 'Cidades', 'Economia', 'Entretenimento']),
    'tudogostoso.com.br': ('Grande portal de receitas, com milhares de receitas, dicas e cardápios.', ['Receitas', 'Doces', 'Carnes', 'Massas', 'Saladas', 'Dicas']),
    'agenciabrasil.ebc.com.br': ('Agência pública de notícias, com cobertura nacional e conteúdo distribuído a outros veículos.', ['Política', 'Economia', 'Direitos humanos', 'Geral', 'Saúde', 'Educação', 'Internacional']),
    'exame.com': ('Revista e portal de negócios, com economia, empresas, carreira e investimentos.', ['Negócios', 'Economia', 'Invest', 'Carreira', 'Tecnologia', 'Mundo']),
    'motor1.com': ('Portal de cultura automotiva, com notícias, testes, lançamentos e carros elétricos.', ['Notícias', 'Testes', 'Lançamentos', 'Elétricos', 'Esportivos', 'Vídeos']),
    'correiobraziliense.com.br': ('Jornal de Brasília, com forte cobertura de política, cidades do Distrito Federal e economia.', ['Política', 'Cidades DF', 'Economia', 'Brasil', 'Mundo', 'Esportes', 'Diversão']),
    'gauchazh.clicrbs.com.br': ('Portal de notícias do Rio Grande do Sul, do grupo RBS, com política, cidades e esportes.', ['Rio Grande do Sul', 'Política', 'Esportes', 'Porto Alegre', 'Economia', 'Entretenimento']),
}
