import React, {useEffect, useState} from 'react';
import {CaduDock} from './CaduDock';
import {WorkspaceAccountMenu} from './WorkspaceFeedback';
import {WorkspaceContextSidebar} from './WorkspaceContextSidebar';
import {VisualIdentity} from './VisualIdentity';
import {openWorkspaceDetail} from '../workspaceNavigation';

const labels = {agencia: 'Agência', equipe: 'Equipe', faturamento: 'Faturamento', integracoes: 'Integrações', planos: 'Plano', perfil: 'Perfil', uso: 'Uso', creditos: 'Créditos'};
const number = value => new Intl.NumberFormat('pt-BR').format(Number(value) || 0);
const money = value => new Intl.NumberFormat('pt-BR', {style: 'currency', currency: 'BRL'}).format(Number(value) || 0);
const parseDate = value => {
  if (!value) return '—';
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
};
const civilDate = value => {
  const parsed = parseDate(value);
  return parsed ? new Intl.DateTimeFormat('pt-BR', {timeZone: 'UTC'}).format(parsed) : value ? String(value) : '—';
};
const dateTime = value => {
  const parsed = parseDate(value);
  return parsed ? new Intl.DateTimeFormat('pt-BR', {dateStyle: 'short', timeStyle: 'short'}).format(parsed) : value ? String(value) : '—';
};
const eventTypes = {invite: 'Convite', welcome: 'Boas-vindas', launch_bonus: 'Bônus inicial', password_reset: 'Redefinição', password_changed: 'Senha alterada'};
const deliveryStatuses = {sent: 'Enviado', delivered: 'Entregue', opened: 'Aberto', clicked: 'Clicado', deferred: 'Adiado', failed: 'Falhou'};
const invoiceStatuses = {paid: 'Paga', overdue: 'Em atraso', pending: 'Pendente'};

function Hidden({name, value}) { return <input type="hidden" name={name} value={value || ''}/>; }
function Metric({label, value, detail, children}) { return <article><span>{label}</span><strong>{value}</strong>{detail && <p>{detail}</p>}{children}</article>; }
function PurchaseModal({bootstrap}) {
  const [order, setOrder] = useState(null); const [billing, setBilling] = useState('prepaid'); const [note, setNote] = useState(''); const [state, setState] = useState('');
  useEffect(() => { const open = event => { setOrder(event.detail); setBilling('prepaid'); setNote(''); setState(''); }; window.addEventListener('cadu-open-purchase', open); return () => window.removeEventListener('cadu-open-purchase', open); }, []);
  if (!order) return null;
  const confirm = async () => { setState('Registrando pedido…'); try { const response = await fetch(bootstrap.endpoints.creditRequest, {method:'POST', credentials:'same-origin', headers:{'Content-Type':'application/json','X-CSRF-Token':bootstrap.csrf}, body:JSON.stringify({tokens:order.tokens || 0, price:order.price || 0, package_name:order.name, billing_mode:billing, note})}); const data = await response.json(); setState(data.message || data.error || 'Não foi possível registrar.'); if (data.success) setTimeout(() => setOrder(null), 2200); } catch { setState('Não foi possível registrar o pedido.'); } };
  return <div className="cadu-ds-purchase-modal" role="dialog" aria-modal="true" aria-labelledby="cadu-purchase-title"><div className="cadu-ds-purchase-modal__card"><button className="cadu-ds-purchase-modal__close" type="button" onClick={() => setOrder(null)} aria-label="Fechar">×</button><span>Pedido interno</span><h2 id="cadu-purchase-title">Confirmar {order.kind === 'plan' ? 'plano' : 'pacote'}</h2><div className="cadu-ds-purchase-modal__summary"><strong>{order.name}</strong><b>{order.price ? money(order.price) + (order.kind === 'plan' ? ' / mês' : '') : 'Preço sob consulta'}</b>{order.tokens ? <small>{number(order.tokens)} créditos de referência</small> : null}</div><label>Forma de cobrança<select value={billing} onChange={event => setBilling(event.target.value)}><option value="prepaid">Pagamento antecipado</option><option value="postpaid">Pós-pago / faturamento financeiro</option></select></label><label>Observação<textarea rows="3" value={note} onChange={event => setNote(event.target.value)} placeholder="Ex.: iniciar no próximo ciclo…"/></label><p className="cadu-ds-purchase-modal__hint">Ao confirmar, o pedido será enviado ao financeiro. Você receberá uma cópia por e-mail e o saldo será liberado após a confirmação interna.</p><footer><button type="button" onClick={() => setOrder(null)}>Voltar</button><button type="button" className="is-primary" onClick={confirm}>Confirmar pedido</button></footer>{state && <p className="cadu-ds-account-notice" role="status">{state}</p>}</div></div>;
}
function AccountPageHeader({eyebrow, title, description}) {
  return <header className="cadu-ds-account-page-header"><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></header>;
}
function CreditSummary({available, lots, lastMovement}) {
  return <section className="cadu-ds-credit-summary" aria-label="Resumo de créditos">
    <div className="cadu-ds-credit-summary__balance"><span>Saldo disponível</span><strong>{number(available)}</strong><p>Créditos compartilhados entre as pessoas e ferramentas deste cliente.</p></div>
    <dl><div><dt>Lotes ativos</dt><dd>{number(lots)}</dd></div><div><dt>Último consumo</dt><dd>{lastMovement ? `${number(lastMovement.amount)} créditos` : 'Nenhum'}</dd><small>{lastMovement?.reason || 'Ainda não há consumo registrado.'}</small></div></dl>
  </section>;
}
function DataTable({columns, rows, empty = 'Nenhum registro disponível.'}) {
  return <div className="cadu-ds-account-table"><table><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td colSpan={columns.length}>{empty}</td></tr>}</tbody></table></div>;
}

function Agency({bootstrap}) {
  const {account, endpoints, csrf, admin, urls} = bootstrap;
  const org = account.organization || {};
  const context = account.agency_context || {};
  const projects = context.projects || [];
  const brands = context.brands || [];
  return <div className="cadu-ds-account-stack">
    <AccountPageHeader eyebrow="Contexto compartilhado" title="O trabalho do cliente" description="Projetos, marcas e pessoas conectadas em um mesmo espaço de trabalho."/>
    {admin ? <form className="cadu-ds-account-form" method="post" action={endpoints.updateOrganization}><Hidden name="_csrf" value={csrf}/><label>Nome da agência<input name="trade_name" defaultValue={org.nome_fantasia || ''} required/></label><label>Razão social<input name="legal_name" defaultValue={org.razao_social || ''}/></label><label>CPF ou CNPJ<input name="document" defaultValue={org.cnpj || ''}/></label><label>CEP<input name="postal_code" defaultValue={org.cep || ''}/></label><label>Logradouro<input name="street" defaultValue={org.logradouro || ''}/></label><label>Número<input name="number" defaultValue={org.numero || ''}/></label><label>Complemento<input name="complement" defaultValue={org.complemento || ''}/></label><label>Bairro<input name="district" defaultValue={org.bairro || ''}/></label><label>Cidade<input name="city" defaultValue={org.cidade || ''}/></label><label>Estado<select name="state" defaultValue={org.estado_sigla || ''}><option value="">Não informado</option>{(account.states || []).map(state => <option key={state.sigla} value={state.sigla}>{state.sigla} — {state.descricao}</option>)}</select></label><footer><span>Esse nome aparece no Workspace e nos contextos da equipe.</span><button>Salvar dados da agência</button></footer></form> : <section className="cadu-ds-account-section"><header><div><span>Identidade da agência</span><h2>{org.nome_fantasia || 'Sua equipe'}</h2></div></header><p className="cadu-ds-account-section-copy">Somente administradores podem alterar os dados da agência. Fale com uma pessoa administradora se precisar ajustar o nome.</p></section>}
    <section className="cadu-ds-account-metrics"><Metric label="Pessoas" value={number(account.people?.length)} detail="com acesso a esta agência"><a href={urls.team}>Gerenciar equipe</a></Metric><Metric label="Projetos" value={number(projects.length)} detail="contextos ativos"><a href={urls.projects}>Ver projetos</a></Metric><Metric label="Marcas" value={number(brands.length)} detail="identidades disponíveis"><a href={urls.brands}>Ver marcas</a></Metric></section>
    <section className="cadu-ds-account-section"><header><div><span>Contextos de trabalho</span><h2>Projetos da agência</h2></div><a href={urls.projects}>Ver todos</a></header><div className="cadu-ds-account-list">{projects.length ? projects.slice(0, 6).map(project => <a href={project.href} key={project.id}><VisualIdentity initials={project.name} label={project.name} color="#176b5e"/><div><b>{project.name}</b><small>{project.brandName || 'Sem marca'} · {number(project.sources)} fontes</small></div><em>{project.status === 'arquivado' ? 'Arquivado' : 'Ativo'}</em></a>) : <p className="cadu-ds-account-empty">Crie o primeiro projeto para formar o contexto da agência.</p>}</div></section>
    <section className="cadu-ds-account-section"><header><div><span>Núcleo da agência</span><h2>Pessoas e marcas</h2></div><a href={urls.team}>Ver equipe</a></header><div className="cadu-ds-account-list">{(account.people || []).slice(0, 5).map(person => <article key={person.id_contato_cliente}><i>{(person.nome_completo || '?').slice(0, 1).toUpperCase()}</i><div><b>{person.nome_completo}</b><small>{person.email} · {person.cargo || person.setor || 'Equipe da agência'}</small></div><em>{person.status ? 'Ativo' : 'Inativo'}</em></article>)}{!account.people?.length && <p className="cadu-ds-account-empty">Convide pessoas para trabalhar nos mesmos contextos.</p>}</div>{brands.length > 0 && <p className="cadu-ds-account-section-copy">{brands.slice(0, 5).map(item => item.name).join(' · ')}{brands.length > 5 ? ' · …' : ''}</p>}</section>
  </div>;
}

function Profile({bootstrap}) {
  const account = bootstrap.account;
  const person = account.current_user || {};
  return <div className="cadu-ds-account-stack">
    <AccountPageHeader eyebrow="Seu lugar na operação" title={`Perfil de ${person.nome_completo || bootstrap.user.name}`} description="Seus dados identificam você em conversas, decisões e convites."/>
    <form className="cadu-ds-account-form" method="post" action={bootstrap.endpoints.updateProfile}><Hidden name="_csrf" value={bootstrap.csrf}/><Hidden name="avatar_badge" value={person.cadu_avatar_badge || bootstrap.user.avatarBadge}/><label>Nome completo<input name="name" defaultValue={person.nome_completo || bootstrap.user.name} required/></label><label>E-mail<input defaultValue={person.email || bootstrap.user.email} disabled/></label><label>Telefone<input name="phone" defaultValue={person.telefone || ''}/></label><footer><span>Seu e-mail é gerenciado pela identidade de acesso.</span><button>Salvar perfil</button></footer></form>
    <section className="cadu-ds-account-section"><header><div><span>Comunicação da conta</span><h2>E-mails disparados por página</h2></div><small>{account.email_catalog?.length || 0} modelos ativos</small></header><DataTable columns={['Página', 'Ação', 'Destinatário', 'Assunto', 'Disparo']} rows={(account.email_catalog || []).map((email, index) => <tr key={email.template || index}><td><b>{email.page}</b></td><td>{email.action}</td><td>{email.recipient}</td><td>{email.subject}<small>{email.template}</small></td><td>{email.timing}</td></tr>)}/></section>
    <section className="cadu-ds-account-section"><header><div><span>Histórico de envio</span><h2>E-mails da equipe</h2></div><small>{account.email_events?.length || 0} registros</small></header><DataTable columns={['Atualização', 'Destinatário', 'Tipo', 'Assunto', 'Status']} empty="Os próximos envios da conta aparecerão aqui." rows={(account.email_events || []).map((event, index) => <tr key={event.id || index}><td>{dateTime(event.last_event_at || event.created_at)}</td><td>{event.recipient_email}</td><td>{eventTypes[event.event_type] || event.event_type}</td><td>{event.subject}</td><td><b>{deliveryStatuses[event.status] || event.status}</b></td></tr>)}/></section>
  </div>;
}

function Team({bootstrap}) {
  const {account, endpoints, csrf, admin} = bootstrap;
  const confirmAction = event => { event.preventDefault(); event.currentTarget.submit(); };
  const pendingInvites = (account.invites || []).filter(item => item.status === 'pending');
  return <div className="cadu-ds-account-stack">
    <AccountPageHeader eyebrow="Acesso do cliente" title="Equipe" description="Pessoas, convites e permissões para trabalhar nos mesmos contextos."/>
    {admin && <section className="cadu-ds-account-section"><header><div><span>Nova pessoa</span><h2>Convidar para a equipe</h2></div></header><form className="cadu-ds-account-inline-form" method="post" action={endpoints.invite}><Hidden name="_csrf" value={csrf}/><label>E-mail<input type="email" name="email" required/></label><label>Acesso<select name="role"><option value="member">Membro</option><option value="admin">Administrador</option></select></label><button>Enviar convite</button></form></section>}
    <section className="cadu-ds-account-section"><header><div><span>Núcleo da agência</span><h2>Pessoas da equipe</h2></div><small>{account.people?.length || 0} pessoas</small></header><p className="cadu-ds-account-section-copy">Projetos, marcas, plano e créditos são compartilhados por esta equipe.</p><div className="cadu-ds-account-list">{(account.people || []).length ? account.people.map(person => <article key={person.id_contato_cliente}><i>{(person.nome_completo || '?').slice(0, 1).toUpperCase()}</i><div><b>{person.nome_completo}</b><small>{person.email} · {person.cargo || person.setor || 'Equipe da agência'}</small></div><em>{person.status ? 'Ativo' : 'Inativo'}</em>{admin && String(person.id_contato_cliente) !== String(bootstrap.user.id) && <div className="cadu-ds-account-row-actions"><form method="post" action={`${endpoints.memberBase}/${person.id_contato_cliente}/papel`}><Hidden name="_csrf" value={csrf}/><select name="role" defaultValue={['admin', 'superadmin'].includes(person.user_type) ? 'admin' : person.user_type || 'client'}><option value="client">Membro</option><option value="admin">Administrador</option><option value="readonly">Somente leitura</option></select><button>Salvar</button></form><form method="post" action={`${endpoints.memberBase}/${person.id_contato_cliente}/status`} onSubmit={confirmAction}><Hidden name="_csrf" value={csrf}/><button className="is-danger">{person.status ? 'Desativar' : 'Reativar'}</button></form></div>}</article>) : <p className="cadu-ds-account-empty">Convide a primeira pessoa para começar a trabalhar em conjunto.</p>}</div></section>
    <section className="cadu-ds-account-section"><header><div><span>Acesso pendente</span><h2>Convites em aberto</h2></div></header><div className="cadu-ds-account-list">{pendingInvites.length ? pendingInvites.map(invite => <article key={invite.id}><i>@</i><div><b>{invite.email}</b><small>{invite.role === 'admin' ? 'Administrador' : 'Membro'} · expira {civilDate(invite.expires_at)}</small></div><em>Pendente</em>{admin && <div className="cadu-ds-account-row-actions"><form method="post" action={`${endpoints.inviteBase}/${invite.id}/reenviar`}><Hidden name="_csrf" value={csrf}/><button>Reenviar</button></form><form method="post" action={`${endpoints.inviteBase}/${invite.id}/cancelar`}><Hidden name="_csrf" value={csrf}/><button className="is-danger">Cancelar</button></form></div>}</article>) : <p className="cadu-ds-account-empty">Nenhum convite pendente.</p>}</div></section>
  </div>;
}

function Plan({account, urls}) {
  const insight = account.insights || {};
  const currentPlan = account.plan?.plan_definition_name || account.plan?.plan_type || 'Plano gratuito';
  const options = account.plan_options || [];
  const fallback = [{plan_name:'Essencial', tokens_monthly_limit:100000, max_users:3}, {plan_name:'Equipe', tokens_monthly_limit:500000, max_users:10}, {plan_name:'Agência', tokens_monthly_limit:2000000, max_users:25}];
  const cards = options.length ? options : fallback;
  const visiblePrices = {Essencial:297, Equipe:697, Agência:1497};
  const openPlan = option => window.dispatchEvent(new CustomEvent('cadu-open-purchase', {detail:{kind:'plan', name:option.plan_name || option.plan_type, price:(option.monthly_price ?? option.price ?? visiblePrices[option.plan_name || option.plan_type] ?? 0), tokens:option.tokens_monthly_limit || option.pd_tokens_monthly_limit || 0, users:option.max_users || option.pd_max_users || 1}}));
  const families = [{name:'Workspace', detail:'Auditoria, conversas, projetos, arquivos e indexação automática.'},{name:'Studio', detail:'Criação, edição e produção de imagens, vídeo e áudio.'},{name:'Planner', detail:'Planejamento, pesquisa, canais, audiências e documentos.'},{name:'Connect', detail:'Contas, relatórios, integrações e dados multi-origem.'},{name:'Skills', detail:'Skills privadas, referências autorizadas e execução contextual.'}];
  return <div className="cadu-ds-account-stack cadu-ds-conversion-page"><AccountPageHeader eyebrow="Seu acesso gratuito" title="Descubra o que seu time pode fazer com o Cadu" description="Você já pode criar projetos, trabalhar com marcas e experimentar todas as famílias. Primeiro encontre valor; escolha um plano apenas quando o uso do time pedir mais capacidade."/><section className="cadu-ds-plan-current cadu-ds-free-hero"><div><span>Você está no começo</span><strong>{currentPlan || 'Plano gratuito'}</strong><p>Sem cobrança automática · projetos e marcas ilimitados · ferramentas para explorar</p></div><a href={urls.usage}>Ver meu primeiro uso</a></section><section className="cadu-ds-account-section cadu-ds-next-step"><header><div><span>Próximo passo</span><h2>Use antes de decidir</h2></div></header><div className="cadu-ds-conversion-steps"><article><b>1</b><strong>Crie um projeto</strong><p>Junte contexto, arquivos e links para seu time trabalhar no mesmo lugar.</p></article><article><b>2</b><strong>Experimente as famílias</strong><p>Planeje, audite, converse e indexe arquivos com o acesso que você já tem.</p></article><article><b>3</b><strong>Amplie quando precisar</strong><p>Os planos aumentam equipe e volume; não escondem a experiência básica.</p></article></div></section><section className="cadu-ds-account-section"><header><div><span>Quando fizer sentido crescer</span><h2>Planos e preços</h2></div><small>Escolha com contexto</small></header><DataTable columns={['Plano', 'Preço mensal', 'Tokens de referência', 'Pessoas', 'Para quem']} empty="Os planos comerciais aparecerão aqui." rows={cards.map((option, index) => { const name = option.plan_name || option.plan_definition_name || option.plan_type || `Plano ${index + 1}`; const isCurrent = option.is_current || name === currentPlan; const price = option.monthly_price ?? option.price ?? visiblePrices[name] ?? 0; return <tr key={option.id || name}><td><b>{name}</b>{isCurrent && <small> · seu acesso</small>}</td><td>{price ? money(price) : 'Grátis'}</td><td>{number(option.tokens_monthly_limit || option.pd_tokens_monthly_limit || 0)}</td><td>{number(option.max_users || option.pd_max_users || 0)}</td><td>{index === 0 ? 'Quem está começando' : index === 1 ? 'Times em rotina' : 'Operações maiores'}</td></tr>; })}/></section><section className="cadu-ds-account-section cadu-ds-family-capabilities"><header><div><span>Já disponível no seu acesso</span><h2>O trabalho do time, por família</h2></div><small>Sem bloqueio artificial</small></header><p className="cadu-ds-account-section-copy">Projetos e marcas são ilimitados. Conversas e ações de IA usam créditos quando processam conteúdo ou geram trabalho; o acesso às famílias continua aberto para você conhecer o produto.</p><div className="cadu-ds-family-grid">{families.map(family => <article key={family.name}><strong>{family.name}</strong><p>{family.detail}</p><span>Explore agora</span></article>)}</div></section></div>;
}

function Usage({account}) {
  const insight = account.insights || {};
  const space = account.space || {};
  const mb = (Number(space.bytes_used || 0) / 1048576).toFixed(2);
  return <div className="cadu-ds-account-stack"><AccountPageHeader eyebrow="Uso do seu time" title="Consumo e espaço" description="Acompanhe o que o seu time usou neste client_id: tokens, conversas, arquivos indexados e espaço ocupado."/><section className="cadu-ds-account-metrics"><Metric label="Tokens neste ciclo" value={`${number(insight.tokens?.used)} de ${number(insight.tokens?.limit)}`}><progress value={insight.tokens?.percentage || 0} max="100"/></Metric><Metric label="Execuções recentes" value={number(account.movements?.length)} detail="registros confirmados"/><Metric label="Espaço usado" value={`${mb} MB`} detail="arquivos deste client_id"/></section><section className="cadu-ds-account-section"><header><div><span>Espaço do time</span><h2>Projetos, marcas e arquivos</h2></div><small>Projetos e marcas ilimitados</small></header><DataTable columns={['Recurso', 'Quantidade / uso', 'Regra']} rows={[<tr key="projects"><td><b>Projetos</b></td><td>{number(space.projects)}</td><td>Ilimitados</td></tr>,<tr key="brands"><td><b>Marcas</b></td><td>{number(account.agency_context?.brands?.length)}</td><td>Ilimitadas</td></tr>,<tr key="files"><td><b>Arquivos indexados</b></td><td>{number(space.files)} · {mb} MB</td><td>Indexação automática; espaço medido por client_id</td></tr>,<tr key="conversations"><td><b>Conversas e ações de IA</b></td><td>{number(account.movements?.length)} execuções recentes</td><td>Disponíveis; consomem créditos quando usam IA</td></tr>,<tr key="tokens"><td><b>Tokens indexados</b></td><td>{number(space.indexed_tokens)}</td><td>Parte do consumo técnico do time</td></tr>]}/></section><section className="cadu-ds-account-section"><header><div><span>Consumo confirmado</span><h2>Atividade recente</h2></div></header><DataTable columns={['Execução', 'Data', 'Referência', 'Créditos']} empty="Ainda não há consumo de IA confirmado." rows={(account.movements || []).map((item, index) => <tr key={item.id || index}><td><b>{item.reason || 'Execução Cadu'}</b></td><td>{dateTime(item.created_at)}</td><td>{item.reference || '—'}</td><td>−{number(item.amount)}</td></tr>)}/></section></div>;
}

function CreditRequestForm({bootstrap}) {
  const [tokens, setTokens] = useState('100000');
  const [price, setPrice] = useState('');
  const [note, setNote] = useState('');
  const [billingMode, setBillingMode] = useState('prepaid');
  const [state, setState] = useState('');
  useEffect(() => { const selectPackage = event => { setTokens(String(event.detail.tokens)); setPrice(String(event.detail.price)); }; window.addEventListener('cadu-select-credit-package', selectPackage); return () => window.removeEventListener('cadu-select-credit-package', selectPackage); }, []);
  const submit = async event => { event.preventDefault(); setState('Enviando…'); try { const response = await fetch(bootstrap.endpoints.creditRequest, {method:'POST', credentials:'same-origin', headers:{'Content-Type':'application/json','X-CSRF-Token':bootstrap.csrf}, body:JSON.stringify({tokens, price, note, billing_mode:billingMode, package_name:`${Number(tokens||0).toLocaleString('pt-BR')} créditos`})}); const data = await response.json(); setState(data.message || data.error || 'Não foi possível enviar.'); if (data.success) { setTokens('100000'); setPrice(''); setNote(''); } } catch { setState('Não foi possível enviar.'); } };
  return <section className="cadu-ds-account-section cadu-ds-credit-request"><header><div><span>Solicitação manual</span><h2>Precisa de mais créditos?</h2></div><small>Sem checkout</small></header><p className="cadu-ds-account-section-copy">Escolha uma faixa e a condição comercial. O valor pode ser definido pelo time na proposta; enviaremos os dados para <b>apolo@centralcomm.media</b>.</p><form className="cadu-ds-account-inline-form" onSubmit={submit}><label>Quantidade de créditos<input type="number" min="1" step="1" value={tokens} onChange={event => setTokens(event.target.value)} required/></label><label>Valor combinado (R$)<input type="number" min="0" step="0.01" value={price} onChange={event => setPrice(event.target.value)} placeholder="Sob consulta"/></label><label>Condição<select value={billingMode} onChange={event => setBillingMode(event.target.value)}><option value="prepaid">Pagamento antecipado</option><option value="postpaid">Pós-pago / faturamento</option></select></label><label className="is-wide">Observação<textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Ex.: liberar hoje para o projeto X" rows="2"/></label><button>Solicitar proposta</button></form>{state && <p className="cadu-ds-account-notice" role="status">{state}</p>}</section>;
}

function Credits({account, bootstrap}) {
  const available = account.credit?.available ?? account.position?.available ?? 0;
  const packages = [{tokens:100000, label:'Extra Essencial', description:'Reforço pontual para uma operação em andamento.'},{tokens:500000, label:'Extra Equipe', description:'Mais margem para planejamento, auditoria e produção.'},{tokens:1000000, label:'Extra Agência', description:'Volume para múltiplos projetos e clientes.'}];
  const choosePackage = pack => window.dispatchEvent(new CustomEvent('cadu-open-purchase', {detail:{kind:'package', name:pack.label, tokens:pack.tokens, price:0}}));
  return <div className="cadu-ds-account-stack"><AccountPageHeader eyebrow="Quando você precisar" title="Créditos acompanham o seu uso" description="A maior parte das contas começa no acesso gratuito. Veja o saldo do seu time, experimente as famílias e peça créditos extras somente quando uma operação real exigir mais volume."/><CreditSummary available={available} lots={account.purchases?.length} lastMovement={account.movements?.[0]}/><section className="cadu-ds-account-section cadu-ds-credit-packages"><header><div><span>Para quando chegar a hora</span><h2>Pacotes de créditos</h2></div><small>Preço sob consulta</small></header><p className="cadu-ds-account-section-copy">Não há cobrança automática nesta tela. Os pacotes são referências de volume; o time define o preço na proposta conforme o uso, a modalidade e o faturamento.</p><DataTable columns={['Pacote', 'Volume', 'Indicado para', 'Preço']} rows={packages.map(pack => <tr key={pack.tokens}><td><b>{pack.label}</b></td><td>{number(pack.tokens)} créditos</td><td>{pack.description}</td><td>Sob consulta</td></tr>)}/><div className="cadu-ds-credit-package-grid">{packages.map(pack => <article key={pack.tokens}><span>{pack.label}</span><strong>{number(pack.tokens)} créditos</strong><p>{pack.description}</p><small>Definido com o time conforme seu caso.</small><button type="button" onClick={() => choosePackage(pack)}>Conhecer esta faixa</button></article>)}</div></section><CreditRequestForm bootstrap={bootstrap}/><section className="cadu-ds-account-section"><header><div><span>Seu histórico</span><h2>Saldo por lote</h2></div></header><DataTable columns={['Pacote', 'Vencimento', 'Disponível', 'Total']} empty="Ainda não há créditos extras. Isso é normal: você pode começar usando o acesso gratuito." rows={(account.purchases || []).map((lot, index) => <tr key={lot.id || index}><td><b>{lot.package_name}</b></td><td>{lot.expires_at ? civilDate(lot.expires_at) : 'Sem vencimento'}</td><td>{number(lot.available)}</td><td>{number(lot.credits)}</td></tr>)}/></section></div>;
}

function Billing({account}) {
  const summary = account.summary || {};
  return <div className="cadu-ds-account-stack"><AccountPageHeader eyebrow="Financeiro do cliente" title="Faturamento" description="Consulte faturas, valores e status de cobrança em um só lugar."/><section className="cadu-ds-account-metrics"><Metric label="Em aberto" value={money(summary.open_total)} detail={`${number(summary.open_count)} faturas`}/><Metric label="Pagas" value={number(summary.paid_count)} detail="no histórico disponível"/><Metric label="Em atraso" value={number(summary.overdue_count)} detail={summary.overdue_count ? 'Requer atenção' : 'Nenhuma pendência vencida'}/></section><section className="cadu-ds-account-section"><header><div><span>Financeiro</span><h2>Histórico de faturas</h2></div></header><DataTable columns={['Fatura', 'Referência', 'Vencimento', 'Status', 'Valor', 'Documento']} empty="Quando houver cobrança registrada, ela aparecerá aqui." rows={(account.invoices || []).map((invoice, index) => <tr key={invoice.id || index}><td><b>{invoice.number}</b></td><td>{invoice.reference || '—'}</td><td>{civilDate(invoice.due_date)}</td><td>{invoiceStatuses[invoice.status_normalized] || invoice.status_normalized}</td><td>{money(invoice.total)}</td><td>{invoice.pdf_safe_url ? <a href={invoice.pdf_safe_url} target="_blank" rel="noreferrer">Abrir PDF</a> : '—'}</td></tr>)}/></section></div>;
}

export function WorkspaceAccount({bootstrap}) {
  const [menuOpen, setMenuOpen] = useState(false);
  const section = bootstrap.section;
  const org = bootstrap.account.organization || {};
  const menuProjects = bootstrap.projects || bootstrap.account.agency_context?.projects || [];
  const menuBrands = bootstrap.brands || bootstrap.account.agency_context?.brands || [];
  const content = section === 'agencia' ? <Agency bootstrap={bootstrap}/> : section === 'perfil' ? <Profile bootstrap={bootstrap}/> : section === 'equipe' ? <Team bootstrap={bootstrap}/> : section === 'planos' ? <Plan account={bootstrap.account} urls={bootstrap.urls}/> : section === 'uso' ? <Usage account={bootstrap.account}/> : section === 'creditos' ? <Credits account={bootstrap.account} bootstrap={bootstrap}/> : <Billing account={bootstrap.account}/>;
  const usagePercent = bootstrap.usagePercent ?? bootstrap.account.position?.usage_percentage ?? 0;
  return <div className="cadu-ds-home-shell cadu-ds-account-shell"><main className="cadu-ds-home-main"><div className="cadu-ds-home-workarea"><CaduDock bootstrap={bootstrap} logo={bootstrap.caduMark} homeUrl={bootstrap.urls.home} userName={bootstrap.user.name} userAvatar={bootstrap.user.avatar} userInitials={bootstrap.user.name?.slice(0, 2).toUpperCase()} accountOpen={menuOpen} accountMenu={<WorkspaceAccountMenu open={menuOpen} onClose={() => setMenuOpen(false)} user={bootstrap.user} links={bootstrap.urls} projects={menuProjects} brands={menuBrands} usagePercent={usagePercent} onManageShortcuts={() => window.location.assign(`${bootstrap.urls.home}#atalhos`)}/>} onOpenAccount={() => setMenuOpen(current => !current)} shortcutItems={bootstrap.dock?.items || []} usagePercent={usagePercent} onNewConversation={() => window.location.assign(bootstrap.urls.newConversation)} onOpenBrand={openWorkspaceDetail} onOpenResource={openWorkspaceDetail} onOpenUsage={() => setMenuOpen(true)}/><WorkspaceContextSidebar mode="account" active={section} links={bootstrap.urls} agencyName={bootstrap.contextName || org.nome_fantasia || org.razao_social || 'Cliente'}/><section className="cadu-ds-account-content"><nav className="cadu-ds-account-tabs" aria-label="Conta">{Object.entries(labels).map(([id, label]) => <a key={id} href={bootstrap.urls[id]} aria-current={id === section ? 'page' : undefined}>{label}</a>)}</nav>{content}</section></div></main><PurchaseModal bootstrap={bootstrap}/></div>;
}
