import React, {useEffect, useRef, useState} from 'react';
import {FORMATS} from '../shared';
import {StudioModal} from './StudioModal';

const MAX_GLOBAL_REFERENCES = 2;

export function BrandPanel({format, setFormat, status, project, selectedGlobalReferences, onGlobalReferencesChange, batchProgress, onPauseQueue, onCancelQueue, onResumeQueue, readOnly, onHistory, onFinalize, onContinue, onExpand, composer}) {
  const [drawer, setDrawer] = useState(null);
  const brand = project?.brand_context || {};
  const brandFonts = brand.fonts || brand.profile?.fonts || [];
  const globalReferences = (brand.assets?.references || []).map((url, index) => ({id: `brand-reference-${index}`, url, label: `Referência global ${index + 1}`}));
  const selectedCount = selectedGlobalReferences.length;
  return <aside className="se-right-panel" aria-label="Assistente, projeto, marca e entrega">
    <header className="se-project-head"><div><span>Projeto e marca</span><strong>Contexto do projeto</strong></div><div className="se-session-actions"><span className={`se-save-state is-${status}`}>{readOnly ? 'Sessão finalizada' : status === 'saving' ? 'Salvando rascunho' : status === 'synced' ? 'Sessão sincronizada' : 'Rascunho local'}</span>{readOnly ? <button type="button" onClick={onContinue}>Continuar</button> : <button type="button" onClick={onFinalize}>Finalizar</button>}</div></header>
    <section className="se-panel-section se-assistant-content">{composer}</section>
    <details className="se-panel-section se-brand-content" open><summary><h2>Marca</h2></summary><span className="se-brand-label">Cores</span>{brand.palette?.length ? <div className="se-brand-swatches">{brand.palette.slice(0, 5).map(color => <i key={typeof color === 'string' ? color : color.hex} style={{background: typeof color === 'string' ? color : color.hex}} title={typeof color === 'string' ? color : color.hex}/>)}</div> : <span className="se-brand-empty">Selecione um projeto para carregar as cores.</span>}<span className="se-brand-label">Tipografia</span><strong className="se-type-preview">{brandFonts.length ? brandFonts.slice(0, 2).map(font => typeof font === 'string' ? font : font.family).filter(Boolean).join(' · ') : 'Tipografia não definida'}</strong><button type="button" className="se-text-button" onClick={() => setDrawer('guidelines')}>Abrir diretrizes</button>{globalReferences.length > 0 && <button type="button" className="se-text-button" onClick={() => setDrawer('references')}>Referências do projeto ({selectedCount ? `${selectedCount} em uso` : `${globalReferences.length} disponíveis`})</button>}</details>
    <details className="se-panel-section se-delivery-content" open><summary><h2>Entrega</h2></summary><label>Formato<div className="se-format-options">{FORMATS.map(item => <button type="button" key={item} className={format === item ? 'is-active' : ''} onClick={() => setFormat(item)}>{item}</button>)}</div></label>{batchProgress && batchProgress.status !== 'completed' && <div className="se-queue-state"><strong>Fila: {batchProgress.completed}/{batchProgress.total}</strong><span>Gerando uma peça por vez.</span></div>}</details>
    {drawer === 'guidelines' && <StudioModal title="Diretrizes da marca" onClose={() => setDrawer(null)}><div className="se-brand-drawer"><p>{brand.brand_summary || 'Nenhuma diretriz descritiva foi cadastrada para esta marca.'}</p>{brand.creative_guidelines?.length ? <section><h3>Direção criativa</h3><ul>{brand.creative_guidelines.map(item => <li key={item}>{item}</li>)}</ul></section> : null}{brand.mandatory_elements?.length ? <section><h3>Obrigatórios</h3><ul>{brand.mandatory_elements.map(item => <li key={item}>{item}</li>)}</ul></section> : null}{brand.forbidden_elements?.length ? <section><h3>Evitar</h3><ul>{brand.forbidden_elements.map(item => <li key={item}>{item}</li>)}</ul></section> : null}</div></StudioModal>}
    {drawer === 'references' && <StudioModal title="Referências do projeto" onClose={() => setDrawer(null)}><div className="se-brand-drawer"><p>Escolha até {MAX_GLOBAL_REFERENCES} imagens do projeto para acompanhar as próximas edições como referência de estilo. Elas orientam por semelhança e não substituem a peça.</p>{globalReferences.length ? <div className="se-global-reference-list">{globalReferences.map(reference => { const checked = selectedGlobalReferences.includes(reference.id); const full = !checked && selectedCount >= MAX_GLOBAL_REFERENCES; return <label key={reference.id} className={full ? 'is-disabled' : ''}><input type="checkbox" checked={checked} disabled={full} onChange={() => onGlobalReferencesChange(checked ? selectedGlobalReferences.filter(id => id !== reference.id) : [...selectedGlobalReferences, reference.id].slice(0, MAX_GLOBAL_REFERENCES))}/><img src={reference.url} alt=""/><span>{reference.label}</span></label>; })}</div> : <p>Nenhuma referência disponível neste projeto.</p>}{selectedCount > 0 && <button type="button" className="se-text-button" onClick={() => onGlobalReferencesChange([])}>Não usar referências do projeto</button>}</div></StudioModal>}
  </aside>;
}
